.github/workflows/add_to_project_board.yml

Adds an action that adds created issues to the Ingest Docs Project Board.

Add action add created issue to project board

---

docs/en/ingest-arch/11-lsenrichfields.asciidoc
docs/en/ingest-arch/12-lspq.asciidoc

Related: #25 
More content and structure for:

IngestArch: Apply structure to ls-enrichment and ls-pq

---

docs/en/ingest-arch/1-agent-to-es.asciidoc
docs/en/ingest-arch/10-ls-enrich.asciidoc
docs/en/ingest-arch/11-lsenrichfields.asciidoc
docs/en/ingest-arch/12-lspq.asciidoc
docs/en/ingest-arch/13-multitenant.asciidoc
docs/en/ingest-arch/14-ea-ls-es.asciidoc
docs/en/ingest-arch/15-proxy.asciidoc
docs/en/ingest-arch/1a-agent.asciidoc
docs/en/ingest-arch/1b-apis.asciidoc
docs/en/ingest-arch/2-custom.asciidoc
docs/en/ingest-arch/6b-filebeat-es.asciidoc
docs/en/ingest-arch/index.asciidoc

Pulled in top level topic for 2-Custom integrations
Made corrections, and more content and structure
Related: #25

IngestArch: Add more content and structure to architectures

---

docs/en/ingest-arch/3-schemamod.asciidoc
docs/en/ingest-arch/3a-runtime-fields.asciidoc
docs/en/ingest-arch/3b-ingest-pipelines.asciidoc
docs/en/ingest-arch/3c-agent-processors.asciidoc
docs/en/ingest-arch/index.asciidoc

Related: #34
ToDo: 
* Add structure, section titles, references, and writing prompts
* Uncomment include statement in index to pull content into book. (Currently, the pages aren't linked and won't show up in a build or preview.)

IngestArch: Set up nested pages for schema mod

---

docs/en/ingest-arch/1-agent-to-es.asciidoc
docs/en/ingest-arch/11-lsenrichfields.asciidoc
docs/en/ingest-arch/12-lspq.asciidoc
docs/en/ingest-arch/13-multitenant.asciidoc
docs/en/ingest-arch/14-ea-ls-es.asciidoc
docs/en/ingest-arch/15-proxy.asciidoc
docs/en/ingest-arch/16-agent-kafka.asciidoc
docs/en/ingest-arch/1x-agent-ls.asciidoc
docs/en/ingest-arch/2-custom.asciidoc
docs/en/ingest-arch/6b-filebeat-es.asciidoc
docs/en/ingest-arch/8-ls-input.asciidoc
docs/en/ingest-arch/index.asciidoc

IngestArch: Restructure source files and include statements

---

docs/en/ingest-arch/1-agent-to-es.asciidoc
docs/en/ingest-arch/1x-agent-ls.asciidoc

IngestArch: Restructure high-level archs to pull in flavors

---

docs/en/ingest-arch/1-agent-to-es.asciidoc
docs/en/ingest-arch/15-proxy.asciidoc
docs/en/ingest-arch/index.asciidoc

IngestArch: Adjust TOC structure and links for use cases

---

docs/en/ingest-arch/13-multitenant.asciidoc
docs/en/ingest-arch/16a-agent-kafka-essink.asciidoc
docs/en/ingest-arch/16b-agent-kafka-ls.asciidoc
docs/en/ingest-arch/1a-agent.asciidoc

IngestArch: Streamlining content

---

docs/en/ingest-arch/15-proxy.asciidoc
docs/en/ingest-arch/8-ls-input.asciidoc

Incorporate more review comments from #62

IngestArch: Add more review comments

---

docs/en/ingest-arch/10-ls-enrich.asciidoc
docs/en/ingest-arch/14-ea-ls-es.asciidoc
docs/en/ingest-arch/arch-list.asciidoc
docs/en/ingest-arch/index.asciidoc

Related: #70 
**PREVIEWS:** 
* https://ingest-docs_77.docs-preview.app.elstc.co/guide/en/ingest/master/index.html
* https://ingest-docs_77.docs-preview.app.elstc.co/guide/en/ingest/master/use-case-arch.html
* https://ingest-docs_77.docs-preview.app.elstc.co/guide/en/ingest/master/ls-enrich.html
* https://ingest-docs_77.docs-preview.app.elstc.co/guide/en/ingest/master/ls-networkbridge.html

IngestArch: Refine details for Logstash use cases

---

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc

Manual backport of #154 to 8.7

[Backport] [8.7] [154] Update troubleshooting.asciidoc

---

.gitignore

Add `./idea/` to `.gitignore` for Goland IDE

---

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc

- [Add note about root/admin privilege to install / uninstall agents (#199)](https://github.com/elastic/ingest-docs/pull/199)

[8.7] Add note about root/admin privilege to install / uninstall agents (#199)

---

.github/ISSUE_TEMPLATE/docs-request.yaml

Fix typo in docs issue template title.

Fix typo in docs issue template title.

---

docs/en/ingest-arch/10-ls-enrich.asciidoc
docs/en/ingest-arch/12-lspq.asciidoc
docs/en/ingest-arch/13-multitenant.asciidoc
docs/en/ingest-arch/14-ea-ls-es.asciidoc

Related: #70
**PREVIEW:** https://ingest-docs_217.docs-preview.app.elstc.co/guide/en/ingest/master/agent-ls.html

IngestArch: Update resources for Agent to Logstash

---

docs/en/ingest-management/commands.asciidoc

required to match new behavior from elastic/elastic-agent#2890

update status documentation 

---

docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc

Fixing images and updated links of the page https://www.elastic.co/guide/en/fleet/master/scaling-on-kubernetes.html

fixing links with updated urls

---

docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc

Adding some details for the initContainers as per customer request

adding initcontainers explanation

---

docs/en/ingest-arch/13-multitenant.asciidoc

Fixes: #218 
**Preview:** https://ingest-docs_333.docs-preview.app.elstc.co/guide/en/ingest/master/ls-multi.html

IngestArch: Add config example for Logstash multi-tenant arch

---

docs/en/ingest-management/fleet/fleet-api-docs.asciidoc

- Resolves https://github.com/elastic/security-docs/issues/3329
- Relates to https://github.com/elastic/security-docs/pull/3661

Adds tip about creating Elastic Defend policy using Fleet API

---

docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc

Follow-on work to https://github.com/elastic/ingest-docs/pull/336
Addresses feedback in https://github.com/elastic/ingest-docs/issues/68

Address feedback on Kafka output docs

---

docs/en/ingest-management/commands.asciidoc

Related issues:
https://github.com/elastic/elastic-agent/pull/2745 
https://github.com/elastic/elastic-agent/pull/3345

Add documentation for the `logs` command

---

docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc

Fixing the 8.10 release notes to address a comment in the 8.10 changelog PR: https://github.com/elastic/elastic-agent/pull/3398

Fix IoC note in 8.10 Release Notes

---

docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc

Manual backport of #485 to 8.9

[Backport] [8.9] [485] Update PGP key known issue

---

.backportrc.json

Add 8.11 to backport tool branch list.

Update .backportrc.json with 8.11

---

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc

which is doubled during upgrades.

Update the text around how much disk space is required by agent.

---

docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc

Hi team, it seems the link moved, fixed it.

Fixed broken link to KSM sharding

---

docs/en/ingest-management/integrations/integrations.asciidoc

This is a manual forward-port of #709 (I'm not doing the port the usual way because I'm strangely, frustratingly unable to checkout the 8.11 branch).

Update integrations page with spaces warning

---

docs/en/ingest-management/beats-agent-comparison.asciidoc

Disk queue: update agent compatibility (forward fit)

---

docs/en/ingest-management/data-streams.asciidoc

Manual backport of #723 to main

[Backport] [main] [723] Update data-streams.asciidoc

---

docs/en/ingest-management/processors/processor-translate_sid.asciidoc

This is a manual forward-port of  https://github.com/elastic/ingest-docs/pull/734

Remove beta tag for translate_sid processor

---

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc

I merged without noticing the comments in https://github.com/elastic/ingest-docs/pull/730/files so this fixes that.

Fix below/above terms for troubleshooting page

---

.backportrc.json
.mergify.yml

Updates the configuration files to add the 8.12 branch

Adds 8.12 branch to backport and mergify configs

---

docs/en/ingest-management/beats-agent-comparison.asciidoc

Updating the agent vs beats compatibility

Updating the agent vs beats compatibility

---

.backportrc.json
.mergify.yml

Updates configuration files to add the 8.13 branch

Add 8.13 branch to backport and mergify configs

---

docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc

Small section that adds some info for autodiscovery template definition for K8s

Adding info for conditions for autodiscovery

---

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc

Fixes a rather embarrassing typo. :-)

Update troubleshooting.asciidoc to fix 'syntethic' typo

---

docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc

Rel: https://github.com/elastic/ingest-docs/issues/1109

Add missing number signs for Fleet Server Release Notes links

---

docs/en/ingest-management/fleet/air-gapped.asciidoc

Make things more explicit in requirements

Clarify EPR & Artifact registry requirement for Air Gapped

---

docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc

This adds a known issue to the 7.17.23 release notes for bug https://github.com/elastic/elastic-agent/issues/5259

Add known issue for 7.17.23 to 8.14/8.15 upgrade

---

docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc

See https://github.com/elastic/beats/issues/40705
- Relates https://github.com/elastic/beats/pull/40767

Add known issue that Beats do not recover from transient network errors

---

docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc

Update the statements related to EA > Kafka > LS > ES to remove the mention of testing and make it "supported"

[DOCS] Refine docs about EA > Kafka > LS > ES

---

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
docs/en/ingest-management/tab-widgets/event-logging-widget.asciidoc
docs/en/ingest-management/tab-widgets/event-logging.asciidoc

Follow up from the Beats PR: https://github.com/elastic/beats/pull/41808

Fix Elastic-Agent event logger documentation

---

docs/en/ingest-management/elastic-agent/example-kubernetes-standalone-agent-helm.asciidoc

Closes: https://github.com/elastic/ingest-docs/issues/1577

Fix typo in k8s standalone agent example

---

docs/en/ingest-management/fleet/fleet-server-secrets.asciidoc

Fix flag in fleet-server-secrets page.

--fleet-server-cert-key-passphrase-path -> --fleet-server-cert-key-passphrase
