- docs/en/ingest-management/index.asciidoc
> [8.7] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `8.5`:
> [8.5] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `8.4`:
> [8.4] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `8.3`:
> [8.3] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `8.2`:
> [8.2] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `8.0`:
> [8.0] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `7.16`:
> [7.16] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `7.14`:
> [7.14] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `7.13`:
> [7.13] fix doc build

- docs/en/ingest-management/index.asciidoc
This will backport the following commits from `main` to `7.12`:
> [7.12] fix doc build

- docs/en/ingest-management/processors/processor-decode_duration.asciidoc
- docs/en/ingest-management/processors/processor-move_fields.asciidoc
- docs/en/ingest-management/processors/processors-list.asciidoc
This PR closes [Issue 2545](https://github.com/elastic/observability-docs/issues/2545)
The decode_duration and move_fields processors were added to Beats in 8.6. This PR adds them to the[ processors section](https://www.elastic.co/guide/en/fleet/current/elastic-agent-processor-configuration.html) of the Fleet and Elastic Agent Guide.
> Add decode duration and move fields processors to docs

- docs/en/ingest-management/processors/processor-decode_duration.asciidoc
- docs/en/ingest-management/processors/processor-move_fields.asciidoc
- docs/en/ingest-management/processors/processors-list.asciidoc
This will backport the following commits from `main` to `8.6`:
- [Add decode duration and move fields processors to docs (#98)](https://github.com/elastic/ingest-docs/pull/98)
> [8.6] Add decode duration and move fields processors to docs (#98)

- docs/en/ingest-management/processors/processor-decode_duration.asciidoc
- docs/en/ingest-management/processors/processor-move_fields.asciidoc
- docs/en/ingest-management/processors/processors-list.asciidoc
- [Add decode duration and move fields processors to docs (#98)](https://github.com/elastic/ingest-docs/pull/98)
> [8.7] Add decode duration and move fields processors to docs (#98)

- docs/en/ingest-management/elastic-agent/run-container-common/kibana-fleet-data.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
This pre-emptively fixes some links that will break if we rename `master` to `main` in the docs builds.
> Fix links pointing to 'master'

- docs/en/ingest-management/elastic-agent/run-container-common/kibana-fleet-data.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
- [Merge pull request #156 from kilfoyle/2521/master-links](https://github.com/elastic/ingest-docs/pull/156)
> [8.7] Merge pull request #156 from kilfoyle/2521/master-links

- docs/en/ingest-management/elastic-agent/run-container-common/kibana-fleet-data.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
This will backport the following commits from `main` to `8.6`:
- [Merge pull request #156 from kilfoyle/2521/master-links](https://github.com/elastic/ingest-docs/pull/156)
> [8.6] Merge pull request #156 from kilfoyle/2521/master-links

- docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
Removes the Subcategories feature from the 8.7 Release Notes since the feature is deferred to 8.8.
Closes: #162
> Remove Subcategories feature from 8.7 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
- Remove Subcategories feature from 8.7 Release Notes (2a17a04e)
> [8.7] Remove Subcategories feature from 8.7 Release Notes

- docs/en/ingest-management/elastic-agent/installation-layout.asciidoc
- docs/en/ingest-management/tab-widgets/install-layout.asciidoc
This PR modifies the Installation Layout documentation for Elastic Agent.  It adds instructions to the MacOS, Linux, and Windows tabs on customizing the installation base path. 
As of this writing, we do not have a way to customize the installation base path for Debian or RPM packaged Elastic Agents.  So the instructions in those two tabs remain unchanged.
Corresponding implementation PR: https://github.com/elastic/elastic-agent/pull/2500
> Add instructions on customizing installation base path for Elastic Agent

- docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
The known issue that "may prevent upgrades scheduled to execute at a later time from running" is pointing to the wrong GH issue.
The original PR https://github.com/elastic/observability-docs/pull/2726 correctly states:
> Add https://github.com/elastic/elastic-agent/issues/2343 as a known issue for 8.6.x releases
but  https://github.com/elastic/elastic-agent/issues/2342 was used instead.
This PR fixes that.
> Change the known issue number to pint to the correct one

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.10 Fleet & Agent Release Notes:
- Fleet: No PRs from the [Kibana 7.17.10 release notes PR](https://github.com/elastic/kibana/pull/155188)
- Fleet Server: [No BC1 changelog for 7.17.10](https://github.com/elastic/fleet-server/tree/affa52ad114d0376e174902cbb1520f83dbd1b2f/changelog/fragments)
- Elastic Agent: [No changes listed in the 7.17.10 BC1 summary](https://staging.elastic.co/7.17.10-e7809e80/summary-7.17.10.html)
**Preview**
> Add Fleet & Agent 7.17.10 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
Adds a missing entry to the 8.7.1 RN:
Rel: https://github.com/elastic/elastic-agent/pull/2577
> Add Agent PR 2448 to 8.7.1 release notes

- docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
- [Merge pull request #183 from kilfoyle/2577/add-8.7.1rn](https://github.com/elastic/ingest-docs/pull/183)
> [8.8] Merge pull request #183 from kilfoyle/2577/add-8.7.1rn

- docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
- [Merge pull request #183 from kilfoyle/2577/add-8.7.1rn](https://github.com/elastic/ingest-docs/pull/183)
> [8.7] Merge pull request #183 from kilfoyle/2577/add-8.7.1rn

- docs/en/ingest-management/elastic-agent/installation-layout.asciidoc
- docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Reverts elastic/ingest-docs#160
Unfortunately, installing Elastic Agent in a custom base path does not work with Endpoint (yet).  As such we've decided to disallow users from using this feature until we have a clear path forward on how to make this feature work with Endpoint.
> Revert "Add instructions on customizing installation base path for Elastic Agent"

- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Add a description of how the service token value and path env vars are used in agent container mode.
Follow up to: https://github.com/elastic/elastic-agent/pull/2576
> Add precedent info for service token path and value in agent container

- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
- [Add precedent info for service token path and value in agent container (#188)](https://github.com/elastic/ingest-docs/pull/188)
> [8.8] Add precedent info for service token path and value in agent container (#188)

- docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Create a new entry for a known issue of agent not loading fleet configuration when upgrading from a version using unencrypted config `fleet.yml` to encrypted one `fleet.enc`
> Add known issue for agent 8.6.2 about not migrating unencrypted config

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Right at the top of the Agent & Fleet [Command Reference main page](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html) we have a note about needing root / Administrator privileges to run commands. We should have a similar note at the top of the Install [Elastic Agents main page](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html), since that's where users planning to install Agent are most likely to see it.
Preview:
> Add note about root/admin privilege to install / uninstall agents

- docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
This PR replaces https://github.com/elastic/observability-docs/pull/2844.
> Add note on location of proxy settings for artifact download

- docs/en/ingest-management/tab-widgets/run-agent-image/content.asciidoc
- [Update content.asciidoc (#182)](https://github.com/elastic/ingest-docs/pull/182)
> [8.8] Update content.asciidoc (#182)

- docs/en/ingest-management/tab-widgets/run-agent-image/content.asciidoc
- [Update content.asciidoc (#182)](https://github.com/elastic/ingest-docs/pull/182)
> [8.7] Update content.asciidoc (#182)

- docs/en/ingest-management/security/certificates.asciidoc
- [Update certificates.asciidoc (#179)](https://github.com/elastic/ingest-docs/pull/179)
> [8.7] Update certificates.asciidoc (#179)

- docs/en/ingest-management/security/certificates.asciidoc
- [Update certificates.asciidoc (#179)](https://github.com/elastic/ingest-docs/pull/179)
> [8.8] Update certificates.asciidoc (#179)

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
- docs/en/ingest-management/fleet/fleet-settings.asciidoc
This adds a "beta" preview notice for the FQDN feature, as requested [here](https://github.com/elastic/ingest-dev/issues/1641#issuecomment-1547677711). The [Fleet UI settings](https://www.elastic.co/guide/en/fleet/current/fleet-settings.html) page and the [feature flags section](https://www.elastic.co/guide/en/fleet/current/elastic-agent-standalone-feature-flags.html) of the standalone Agent docs are updated. Similar PR for the Beats docs is [here](https://github.com/elastic/beats/pull/35466).
I've added a separate note that APM and Endpoint aren't supported (separate because the beta disclaimer is standard text).
---
> Add preview notice for FQDN feature

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- [Add preview notice for FQDN feature (#211)](https://github.com/elastic/ingest-docs/pull/211)
> [8.8] Add preview notice for FQDN feature (#211)

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- [Add preview notice for FQDN feature (#211)](https://github.com/elastic/ingest-docs/pull/211)
> [8.7] Add preview notice for FQDN feature (#211)

- docs/en/ingest-management/commands.asciidoc
- [Update commands.asciidoc (#214)](https://github.com/elastic/ingest-docs/pull/214)
> [8.8] Update commands.asciidoc (#214)

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
- [Add Fleet & Agent 8.8.0 release notes (#219)](https://github.com/elastic/ingest-docs/pull/219)
> [8.8] Add Fleet & Agent 8.8.0 release notes (#219)

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
This updates the [Run Elastic Agent in a container](https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html) page to add a step to verify the Docker image.
Rel: https://github.com/elastic/dev/issues/2002
Preview
---
> Add instructions to verify Docker install images

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- [Add instructions to verify Docker install images (#224)](https://github.com/elastic/ingest-docs/pull/224)
> [8.8] Add instructions to verify Docker install images (#224)

- docs/en/ingest-management/data-streams.asciidoc
- [Add docs for advanced indexing features (#227)](https://github.com/elastic/ingest-docs/pull/227)
> [8.8] Add docs for advanced indexing features (#227)

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
- docs/en/ingest-management/fleet/fleet-settings.asciidoc
Update the documentation for main and 8.8 to indicate the endpoint security now supports the FQDN feature.
> Endpoint security supports the FQDN feature in 8.8.

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- [Endpoint security supports the FQDN feature in 8.8. (#235)](https://github.com/elastic/ingest-docs/pull/235)
> [8.8] Endpoint security supports the FQDN feature in 8.8. (#235)

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Some scalability settings are missing in the docs from the [Advanced Fleet server options](https://www.elastic.co/guide/en/fleet/current/fleet-server-scalability.html#fleet-server-configuration) list. This adds the missing settings based on the contents of [limits.go](https://github.com/elastic/fleet-server/blob/main/internal/pkg/config/limits.go) (thanks @juliaElastic for pointing to that file!).
Reviewers, I wasn't 100% sure about the settings descriptions so please check carefully and let me know if we need more detail for any of them.
Closes: https://github.com/elastic/observability-docs/issues/2758
[Preview](https://ingest-docs_239.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-server-scalability.html#fleet-server-configuration)
> [Docs] Add missing Fleet scalability options

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
- [[Docs] Add missing Fleet scalability options (#239)](https://github.com/elastic/ingest-docs/pull/239)
> [8.8] [Docs] Add missing Fleet scalability options (#239)

- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
This PR:
- Adds a note to the [Install standalone Elastic Agents](https://www.elastic.co/guide/en/fleet/current/install-standalone-elastic-agent.html) page indicating that the install path can't exceed 103 characters.
- Combines this with the other two notes at the top of that page into a single "restrictions" block.
Preview:
Closes: https://github.com/elastic/ingest-docs/issues/240
> Add file path length restriction for standalone agent

- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
- [Add file path length restriction for standalone agent (#241)](https://github.com/elastic/ingest-docs/pull/241)
> [8.8] Add file path length restriction for standalone agent (#241)

- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
- [Revert "Add file path length restriction for standalone agent (#241)" (#244)](https://github.com/elastic/ingest-docs/pull/244)
> [8.8] Revert "Add file path length restriction for standalone agent (#241)" (#244)

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
This updates the [8.8.0 release notes](https://www.elastic.co/guide/en/fleet/8.8/release-notes-8.8.0.html) with a known issue about file length limits.
Rel: https://github.com/elastic/ingest-docs/issues/240
[Preview](https://ingest-docs_246.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.8.0.html)
---
**collapsed**
---
**expanded**
> Add known issue for file path length

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
- [Add known issue for file path length (#246)](https://github.com/elastic/ingest-docs/pull/246)
> [8.8] Add known issue for file path length (#246)

- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
- docs/en/ingest-management/migrate-beats-to-agent.asciidoc
- docs/en/ingest-management/quick-starts.asciidoc
Updates links in the Fleet/Agent docs to point to new URLs.
Fixes link errors in https://github.com/elastic/observability-docs/pull/2990.
> Update links to ingest/getting started content

- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
- docs/en/ingest-management/migrate-beats-to-agent.asciidoc
- docs/en/ingest-management/quick-starts.asciidoc
- [Update links to ingest/getting started content (#247)](https://github.com/elastic/ingest-docs/pull/247)
> [8.8] Update links to ingest/getting started content (#247)

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
This adds the 8.8.1 Fleet & Agent Release Notes:
- Fleet adds are from the [Kibana RN PR](https://github.com/elastic/kibana/pull/159159)
- Fleet Server add are from the changelog PR: https://github.com/elastic/fleet-server/pull/2673 
- Elastic Agent adds are from the changelog PR: https://github.com/elastic/elastic-agent/pull/2795
[Preview](https://ingest-docs_251.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.8.1.html)
> Add Fleet & Agent 8.8.1 release notes

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
- [Add Fleet & Agent 8.8.1 release notes (#251)](https://github.com/elastic/ingest-docs/pull/251)
> [8.8] Add Fleet & Agent 8.8.1 release notes (#251)

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
This updates the 8.8.0 Release Notes with a known issue about stalled upgrades.
Preview:
> Add known issue for 8.8.0 stalled upgrade

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
- [Add known issue for 8.8.0 stalled upgrade (#253)](https://github.com/elastic/ingest-docs/pull/253)
> [8.8] Add known issue for 8.8.0 stalled upgrade (#253)

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
This updates the description of the stalled upgrade [known issue](https://www.elastic.co/guide/en/fleet/current/release-notes-8.8.0.html#known-issues-8.8.0) in 8.8.0 to mention the return to a healthy state.
Rel: #253
> Update 8.8.0 known issue for stalled upgrade

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
- [Update 8.8.0 known issue for stalled upgrade (#255)](https://github.com/elastic/ingest-docs/pull/255)
> [8.8] Update 8.8.0 known issue for stalled upgrade (#255)

- .github/ISSUE_TEMPLATE/docs-request.yaml
Adds a general purpose issue template for docs requests. When someone creates an issue using the template, it presents an issue form. The form captures all information required for the issue to be ready for work by a tech writer.
The template is copied and slightly modified from the [Obs docs repo](https://github.com/elastic/observability-docs/blob/main/.github/ISSUE_TEMPLATE/other-request.yaml).
> Add issue template for docs requests

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
On the [Fleet UI settings page](https://www.elastic.co/guide/en/fleet/8.8/fleet-settings.html), The anchors for "Elasticsearch output settings" and "Logstash output settings" don't line up with the actual text, causing the section titles to cut off.
This is a known Asciidoctor limitation for pages that are at the 5th level and below in the navigation tree. Technically, these two sections are subsections of the "Output settings" section on the page, but the usability is not good, and it's reasonable for users to expect the two problem sections to be at the same navigation level as "Fleet Server host settings" and "Agent binary download settings", as reflected in the settings file.
Before (section title is cut off):
After (section title is visible):
Closes: #230
> Fix anchor alignment on Fleet settings page

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- [Fix anchor allignment on Fleet settings page (#260)](https://github.com/elastic/ingest-docs/pull/260)
> [8.8] Fix anchor allignment on Fleet settings page (#260)

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
This adds the 8.8.2 Fleet & Agent Release Notes:
- Fleet adds are from the [Kibana 8.8.2 release notes PR](https://github.com/elastic/kibana/pull/160211)
- Fleet Server [no fragments to add](https://github.com/elastic/fleet-server/tree/b8b0124f40de8bd1d5ceae2c45ed0e1b122360a2/changelog/fragments)
- Elastic Agent additions are from the changelog PR: https://github.com/elastic/elastic-agent/pull/2939
[Preview](https://ingest-docs_275.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.8.2.html)
> Add Fleet & Agent 8.8.2 release notes

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.11 Fleet & Agent Release Notes:
- Fleet: No PRs from the [Kibana 7.17.11 release notes PR](https://github.com/elastic/kibana/pull/160217)
- Fleet Server: [No BC1 changelog entries for 7.17.11](https://github.com/elastic/fleet-server/tree/bc097b6d0b65dc8949b9fb8b10c5696d32f40c27/changelog/fragments)
- Elastic Agent: [No BC1 changelog entries for 7.17.11](https://staging.elastic.co/7.17.11-5a11c283/summary-7.17.11.html)
PREVIEW
> Add Fleet & Agent 7.17.11 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
This will backport the following commits from `main` to `8.9`:
- [Add Fleet & Agent 8.8.2 release notes (#275)](https://github.com/elastic/ingest-docs/pull/275)
> [8.9] Add Fleet & Agent 8.8.2 release notes (#275)

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
- [Add Fleet & Agent 8.8.2 release notes (#275)](https://github.com/elastic/ingest-docs/pull/275)
> [8.8] Add Fleet & Agent 8.8.2 release notes (#275)

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
The troubleshooting guide needs to be updated due to this merge: https://github.com/elastic/elastic-agent/pull/566
Replaces https://github.com/elastic/observability-docs/pull/2849.
> Sensitive information is already being redacted from diagnostics

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
I noticed a small typo in the `fleet-server` attribute. 🙃
> Fix attribute typo

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
This will backport the following commits from `main` to `8.9`:
- [Update fleet-settings.asciidoc (#303)](https://github.com/elastic/ingest-docs/pull/303)
> [8.9] Update fleet-settings.asciidoc (#303)

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- [Update fleet-settings.asciidoc (#303)](https://github.com/elastic/ingest-docs/pull/303)
> [8.8] Update fleet-settings.asciidoc (#303)

- .mergify.yml
- README.md
The stack-docs, security, and observability repos use Mergify to automate backports. This PR copies the method used in observability-docs (https://github.com/elastic/observability-docs/blob/main/.mergify.yml) using backport-specific labels (backport-x.y)
I've created the associated backport labels, and we can merge the PR. However, Mergify must be enabled on the repo before it'll begin automating backports. I have an open request to enable Mergify on the repo here: https://elasticco.atlassian.net/browse/SRE-364 (sorry --- internal link)
Related: #210
> Add mergify config for automated backports

- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
Adding Documentation for generic_logs template for Elastic Agent Hints Autodiscovery scenario in order to collect logs from k8s pods
> Adding generic_logs template for hints autodiscovery

- docs/en/ingest-arch/14-ea-ls-es.asciidoc
- docs/en/ingest-arch/15-proxy.asciidoc
Closes #70
Sets up  distinction between "Logstash as proxy" and generic proxy.
> IngestArch: Differentiate between proxies

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
This adds docs for the new commands to force standalone agent to use a new public GPG key to verify upgrade packages. I also added some brief mention of air-gapped upgrades since it's essential background.
**Preview**
* [Upgrade standalone agents](https://ingest-docs_334.docs-preview.app.elstc.co/guide/en/fleet/master/upgrade-standalone.html#upgrade-standalone) (I've added new sections "Upgrading standalone Elastic Agent in an air-gapped environmment" and "Verifying Elastic Agent package signatures")
* [elastic-agent upgrade command](https://ingest-docs_334.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-cmd-options.html#elastic-agent-upgrade-command) (I've added the new options to this page)
Closes: #335
Rel: https://github.com/elastic/elastic-agent/pull/2246
> Add docs for upgrade package verification with alternate PGP keys

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.12 Fleet & Agent Release Notes:
- Fleet: https://github.com/elastic/kibana/pull/162123 (no RN entries)
- Fleet Server: https://github.com/elastic/fleet-server/tree/305aee56a8b631bf76d23ff7993f451608d12822/changelog/fragments (no fragments)
- Elastic Agent: https://staging.elastic.co/7.17.12-41e66b3b/summary-7.17.12.html (no changelog)
> Add Fleet & Agent 7.17.12 Release Notes

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc
This adds the 8.9.0 Fleet & Agent Release Notes:
- Fleet contents are from the [Kibana RN PR](https://github.com/elastic/kibana/pull/161909)
- Fleet Server contents are from the 8.9.0 fragments and verified by the [changelog PR](https://github.com/elastic/fleet-server/pull/2806)
- Elastic Agent contents are from the 8.9.0 fragments and verified by the [changelog PR](https://github.com/elastic/elastic-agent/pull/3106)
[Preview](https://ingest-docs_341.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.9.0.html)
Closes: https://github.com/elastic/ingest-docs/issues/338
> Add Fleet & Agent 8.9.0 release notes

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Updates the recommended minimums for Elastic Agent as shown (version 8.2):
Rel: https://github.com/elastic/ingest-docs/issues/347
> Update recommended Disk and RSS Mem Size settings - v8.1

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Updates the recommended minimums for Elastic Agent as shown (version 8.2):
Rel: https://github.com/elastic/ingest-docs/issues/347
> Update recommended Disk and RSS Mem Size settings - v8.2

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Updates the recommended minimums for Elastic Agent as shown (version 8.3):
Rel: https://github.com/elastic/ingest-docs/issues/347
> Update recommended Disk and RSS Mem Size settings - v8.3

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Updates the recommended minimums for Elastic Agent as shown (applicable to versions 8.8 and higher):
Closes: https://github.com/elastic/ingest-docs/issues/347
> Update recommended Disk and RSS Mem Size settings for Elastic Agent

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
The Elastic Agent install [minimum requirements](https://www.elastic.co/guide/en/fleet/8.8/elastic-agent-installation.html#_minimum_requirements) mentions the agent version on which the requirements were tested. This isn't really necessary since the product requirements match the docs version, and it's one more thing that we have to maintain with each release (and in the event that we neglect to maintain it, the docs appear inconsistent).
> Remove tested version number from agent minimum install reqs

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This will backport the following commits from `main` to `8.2`:
> [8.2] Remove tested version number from agent minimum install reqs (#360)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This will backport the following commits from `main` to `8.3`:
> [8.3] Remove tested version number from agent minimum install reqs (#360)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This will backport the following commits from `main` to `8.4`:
> [8.4] Remove tested version number from agent minimum install reqs (#360)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This will backport the following commits from `main` to `8.5`:
> [8.5] Remove tested version number from agent minimum install reqs (#360)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This will backport the following commits from `main` to `8.6`:
> [8.6] Remove tested version number from agent minimum install reqs (#360)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This will backport the following commits from `main` to `8.1`:
> [8.1] Remove tested version number from agent minimum install reqs (#360)

- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
PR to manually backport changes that were merged into `main` with the following original PR:  
- https://github.com/elastic/ingest-docs/pull/304
- and https://github.com/elastic/ingest-docs/pull/380
- Closes https://github.com/elastic/elastic-agent/issues/3158
> adding docs for default container in 8.9

- docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
Fixes broken image link in the v8.9 version of the [Scaling Elastic Agent on Kubernetes page](https://www.elastic.co/guide/en/fleet/master/scaling-on-kubernetes.html).
Closes: #395
> Fix images on Elastic Agent K8s Scaling page

- docs/en/ingest-management/commands.asciidoc
Re-closes https://github.com/elastic/elastic-agent/issues/2140
This updates the section on the diagnostics command reference to reflect the updated structure of the diagnostic commands, and also the new `-p` flag.
> Update docs for diagnostic command

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
A few small fixes (the SCRAM mechanism link; the guidance to make sure the Kafka/Logstash/Elasticsearch output type is selected) for the [Kafka output docs](https://www.elastic.co/guide/en/fleet/master/kafka-output-settings.html).
> Small fixes for Kafka output docs

- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Rel: #421 
This updates Fleet's Logstash output type page equivalent to the same for for Kafka and Elasticsearch (I forgot to click Save when making the updates in the original PR).
> Small fix to Fleet's Logstash output type

- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
This will backport the following commits from `main` to `8.10`:
- [Address feedback on Kafka output docs (#420)](https://github.com/elastic/ingest-docs/pull/420)
> [8.10] Address feedback on Kafka output docs (#420)

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
This will backport the following commits from `main` to `8.10`:
- [Small fixes for Kafka output docs (#421)](https://github.com/elastic/ingest-docs/pull/421)
> [8.10] Small fixes for Kafka output docs (#421)

- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
This will backport the following commits from `main` to `8.10`:
- [Small fix to Fleet's Logstash output type (#422)](https://github.com/elastic/ingest-docs/pull/422)
> [8.10] Small fix to Fleet's Logstash output type (#422)

- .mergify.yml
This enables the auto-backport tool to merge from `main` into `8.10`. 
For future reference, I should have updated both [.mergify.yml](https://github.com/elastic/ingest-docs/blob/main/.mergify.yml) and [.backportrc.json](https://github.com/elastic/ingest-docs/blob/main/.backportrc.json) in the same PR. Now I know for next time.
> Update mergify.yml for 8.10

- docs/en/ingest-management/processors/processor-syslog.asciidoc
- Removed the experimental tag for the syslog processor
- Improve documentation of the syslog processor to note that it does not directly handle receiving external messages.
- See elastic/beats#36417
> Remove experimental tag and improve documentation of syslog processor

- docs/en/ingest-arch/15-proxy.asciidoc
Rel: https://github.com/elastic/platform-docs-team/issues/195
> Fix broken link to "Using a proxy server with Elastic Agent and Fleet"

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.13 Fleet & Agent Release Notes:
- Fleet: no RN entries in [Kibana PR](https://github.com/elastic/kibana/pull/165342)
- Fleet Server: [no fragments in bc1](https://github.com/elastic/fleet-server/tree/305aee56a8b631bf76d23ff7993f451608d12822/changelog/fragments)
- Elastic Agent: [no changelog file for bc1](https://staging.elastic.co/7.17.13-d6f555d2/summary-7.17.13.html)
**PREVIEW**
> Add Fleet & Agent 7.17.13 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc
This adds the 8.9.2 Fleet & Agent Release Notes:
- Fleet contents are from the [Kibana RN PR](https://github.com/elastic/kibana/pull/165370)
- Fleet Server - No 8.9.2 fragments.
- Elastic Agent contents are from the [8.9.2 BC1 fragments](https://github.com/elastic/elastic-agent/tree/162ea92bd5d85f543a0746546b8cb5ec4cd8e2f8/changelog/fragments)
[Docs preview](https://ingest-docs_439.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.9.2.html)
Closes: #436
> Add Fleet & Agent 8.9.2 Release Notes

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
This adds links to more detailed docs from the Fleet output settings descriptions. I'll update the Advanced YAML Configuration setting separately once we know which advanced settings to describe for each output type.
Elasticsearch Output settings, for example:
> Add doc links to Fleet UI output settings descriptions

- docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc
This updates the [8.9.0 Release Notes](https://www.elastic.co/guide/en/fleet/8.9/release-notes-8.9.0.html). The change of the agent output `host.name` field to lowercase made in 8.9.0 should be marked as a breaking change.
Rel: https://github.com/elastic/kibana/issues/165642
> Move 8.9.0 RN host.name change to breaking changes section

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Fixes a bad link that's breaking the [8.10 Fleet & Agent Release Notes PR](https://github.com/elastic/ingest-docs/pull/469).
> Fix breaking link in 8.10 troubleshooting docs to known issue 3375

- docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
- docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
Adding documentation information for NETINFO envrionmental variable introdused in this PR: https://github.com/elastic/beats/pull/36506
- Relates https://github.com/elastic/integrations/issues/6674
> Adding information for NETINFO environmental variable

- docs/en/ingest-management/beats-agent-comparison.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/authentication/ssl-settings.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-download.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/structure-config-file.asciidoc
- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
- docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
This PR:
- Adds a "Structure of a config" page briefly describing each component of the `elastic-agent.yml` policy file with links to more detailed sections.
- Adds a new section for the `agent.download` settings.
- Removes the following warnings from throughout the standalone agent docs:
This is just a starting point with gradual improvements expected to follow.
**PREVIEW PAGES**
New ["Structure of a config file" page](https://ingest-docs_433.docs-preview.app.elstc.co/guide/en/fleet/master/structure-config-file.html)
New [agent.download settings page](https://ingest-docs_433.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-standalone-download.html)
Closes: #372
> Add 'Structure of a config file' for standalone agent and remove warnings

- docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
**Problem:** In https://github.com/elastic/docs/pull/2752, we updated the URL prefix (`welcome-to-elastic`) and name for the "Welcome to Elastic Docs" docs. However, we still have some stray links that use the old `/welcome-to-elastic` URL prefix
**Solution:** Updates several outdated links to use an attribute.
> Fix `welcome-to-elastic` links

- docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
**Problem:** [Scaling Elastic Agent on Kubernetes](https://www.elastic.co/guide/en/fleet/current/scaling-on-kubernetes.html) contains a malformed link. Screenshot:
**Solution:** Fix the link syntax.
> Fix malformed link

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-shared-settings.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
This adds output settings that can be applied in the `Advanced YAML configuration` field in Fleet's Elasticsearch, Logstash, and Kafka output settings UIs. Settings are based off of the respective [Filebeat output settings](https://www.elastic.co/guide/en/beats/filebeat/current/configuring-output.html) pages.
Preview pages:
- [Elasticsearch advanced YAML](https://ingest-docs_465.docs-preview.app.elstc.co/guide/en/fleet/master/es-output-settings.html#es-output-settings-yaml-config)
- [Logstash advanced YAML](https://ingest-docs_465.docs-preview.app.elstc.co/guide/en/fleet/master/ls-output-settings.html#ls-output-settings-yaml-config)
- [Kafka advanced YAML](https://ingest-docs_465.docs-preview.app.elstc.co/guide/en/fleet/master/kafka-output-settings.html#kafka-output-settings-yaml-config) …
> Add advanced YAML config for Fleet UI output settings docs

- docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
This adds a note to the Elastic Agent install instructions to note that ARM packages are available in addition to what's shown on the UI.
---
**Fleet managed agent instructions**
**Standalone agent instructions**
> Update Elastic Agent install docs to mention ARM binaries

- docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
This adds the 8.10.2 Fleet & Agent Release Notes:
- Fleet contents are copied from the [Kibana RN PR](https://github.com/elastic/kibana/pull/166895)
- Fleet Server - no new fragments in [BC1 fragments](https://github.com/elastic/fleet-server/tree/7f1fd0d97ee51456d323328e982ac8b8fc7a7801/changelog/fragments )
- Elastic Agent contents are from the [BC1 fragments](https://github.com/elastic/elastic-agent/tree/b0c688f63bc05c61d23b1c26983f2f5d02011ff1/changelog/fragments)
---
> Add Fleet & Agent 8.10.2 Release Notes

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/structure-config-file.asciidoc
Adds links to the tutorial about using standalone Elastic Agent to monitor nginx logs.
> Add links to the newly added standalone tutorial

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
Add [enrich](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-elastic_agent.html#plugins-inputs-elastic_agent-ecs_metadata) option to none in the configuration example to prevent Logstash from adding the field like `event.original`, which can break integrations like apache.access (which expects the field event.original to not exist before the ingest pipeline). This should also slightly improve input performances, because it avoids Logstash to perform unuseful work.
An alternative configuration could be:
```
input {
elastic_agent {
port => 5044
enrich => [ssl_peer_metadata, source_metadata]
}
}
```
> Add option enrich none to input

- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
This adds the following highlighted note to the [Kafka output settings UI documentation](https://www.elastic.co/guide/en/fleet/8.10/kafka-output-settings.html#kafka-output-settings). 
Rel: https://github.com/elastic/kibana/issues/166135
> Add warning about quotation marks to Kafka output docs

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Removes outdated beta tags for the Preview API Request feature, for example from [here](https://www.elastic.co/guide/en/fleet/8.10/agent-policy.html), [here](https://www.elastic.co/guide/en/fleet/8.10/add-integration-to-policy.html), and [here](https://www.elastic.co/guide/en/fleet/current/fleet-api-docs.html#create-agent-policy-api).
> Remove beta tags from Fleet API Preview request

- docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
Documents the bug reported in https://github.com/elastic/kibana/issues/166553 and the workaround. Added as a known issue to the [8.10.0 release notes](https://www.elastic.co/guide/en/fleet/current/release-notes-8.10.0.html). 
[PREVIEW](https://ingest-docs_523.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.10.0.html#known-issues-8.10.0) (see the second "Known issues" link).
> Add known issue and resolution for Fleet's KQL processing changes

- docs/en/ingest-management/integrations/install-integration-assets.asciidoc
This adds the restrictions explained in https://github.com/elastic/ingest-docs/issues/324 to the [Install integration assets](https://www.elastic.co/guide/en/fleet/8.8/install-uninstall-integration-assets.html#install-integration-assets) instructions.
@lucabelluccini @yomduf  Please let me know if anything needs fixing.
> Add notes about asset installation on multiple spaces

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/security/certificates.asciidoc
This updates the two examples on the Elastic Agent [commands](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-install-command) page and a similar example on the [configure SSL/TLS](https://www.elastic.co/guide/en/fleet/current/secure-connections.html#_encrypt_traffic_between_elastic_agents_fleet_server_and_elasticsearch) page to include the parameter to specify the Fleet Server port.
Closes: https://github.com/elastic/ingest-docs/issues/233
> Add 'fleet-server-port' parameter to agent install examples

- docs/en/ingest-management/integrations/install-integration-assets.asciidoc
This will backport the following commits from `main` to `8.11`:
- [Add notes about asset installation on multiple spaces (#504)](https://github.com/elastic/ingest-docs/pull/504)
> [8.11] Add notes about asset installation on multiple spaces (#504)

- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
As part of https://github.com/elastic/elastic-agent/issues/3161 we implemented the functionality to support multiple containers for Hints Autodiscovery for Elastic Agent.
This PR adds the extra documentation information for Elastic Agent users for support of multiple containers for Hints Autodiscovery
> Updating doc for Hints Autodiscovery for  multiple containers

- docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc
This adds the 8.10.3 Fleet & Agent Release Notes:
- Fleet contents are copied from the [Kibana RN PR TBD](TBD)
- Fleet Server - no new fragments in [BC1 fragments](https://github.com/elastic/fleet-server/tree/badea41a034a0080a24aaaa0c34a94c18ca6fcda/changelog/fragments)
- Elastic Agent contents are from the [BC1 fragments](https://github.com/elastic/elastic-agent/tree/7ae7e8f672dfd45516cbd46f7b9c11848f622cb3/changelog/fragments)
Closes: #551
---
> Add Fleet & Agent 8.10.3 Release Notes

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.14 Fleet & Agent Release Notes:
- Fleet: no RN entries in [Kibana PR TBD](TBD)
- Fleet Server: [no fragments in bc1 - TBD](TBD)
- Elastic Agent: [no changelog file for bc1 - TBD](TBD)
---
> Add Fleet & Agent 7.17.14 Release Notes

- docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
This adds steps to restart a stalled upgrade process for an individual or multiple agents. I expect we'll need a few small changes once the more granular upgrade status is available.
Note that I purposefully have not included screen captures. We find that they can go out of date very quickly, and also users typically don't rely on them unless the UI is complex. In this case I think just having the steps should suffice.
@juliaElastic, thanks for putting so much detail in the PR! That and your demo were very helpful.
Closes: #500 
PREVIEW:
[Restart upgrade for a single agent](https://ingest-docs_568.docs-preview.app.elstc.co/guide/en/fleet/master/upgrade-elastic-agent.html#restart-upgrade-single)
[Restart upgrade for multiple agents](https://ingest-docs_568.docs-preview.app.elstc.co/guide/en …
> Add docs for agent upgrade restart feature

- docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/inputs/inputs-list.asciidoc
- docs/en/ingest-management/index.asciidoc
Adds a list of inputs that can be specified for the `type` parameter in an `elastic-agent.yml` file. I've verified the list against the associated spec files in v8.10 and main.
@belimawr This is the same as what was in [#489](https://github.com/elastic/ingest-docs/pull/489) except that I've removed some inputs that shouldn't have been included (I noticed they weren't in the `main` or `8.10` versions of the spec file). 
[DOCS PREVIEW](https://ingest-docs_561.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-inputs-list.html)
Rel: https://github.com/elastic/ingest-docs/issues/374
Rel: https://github.com/elastic/ingest-docs/issues/556
> Add list of Elastic Agent inputs for standalone configuration

- docs/en/ingest-management/elastic-agent/installation-layout.asciidoc
- docs/en/ingest-management/tab-widgets/install-layout.asciidoc
This is essentially a re-do of https://github.com/elastic/ingest-docs/pull/160 which was reverted.
In https://github.com/elastic/ingest-dev/issues/1609 the install command's `--base-path` option was temporarily hidden. It's re-enabled now and should also be re-added to the documentation. See [comment](https://github.com/elastic/ingest-dev/issues/1609#issuecomment-1533505729) and [comment](https://github.com/elastic/ingest-dev/issues/1609#issuecomment-1746078531).
@ycombinator I've tagged this to go into 8.10 and later docs. Do you know if it should go into 8.9 as well?
PREVIEWS
---
Linux
Mac
Windows
> Re-add docs for install '--base-path' parameter

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server.asciidoc
- docs/en/ingest-management/fleet/fleet-server.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/overview.asciidoc
- docs/en/ingest-management/serverless-restrictions.asciidoc
This updates the Fleet and Elastic Agent docs with restrictions for Serverless:
- Fleet restrictions added to [Add a Fleet Server](https://ingest-docs_516.docs-preview.app.elstc.co/guide/en/fleet/master/add-a-fleet-server.html) and [Set up Fleet Server](https://ingest-docs_516.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-server.html)
- Agent restrictions added to [Install Elastic Agents](https://ingest-docs_516.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-installation.html)
- Both of the above included on a new "Restrictions for Elastic Serverless" page
Notes:
- These changes are behind a feature flag.
- Separately and later, we'll rework the Fleet Server pages to be less prominent: [issue](https://github.com/elastic/ingest-docs/issues/585).
Closes: #582
> Add Serverless restrictions to Fleet & Agent docs

- docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
A customer reported that this CPU spike issue wasn't documented in the Fleet & Elastic Agent Release Notes, so this fixes that based on this really nice [Knowledge Base article]( https://support.elastic.co/knowledge/72d18596).
@brian-mckinney and @gabriellandau  I think you two fixed this issue. Would you mind checking that my descriptions are correct, below? By the way, for any unusual issues like this that cross products, please let me or one of the security docs folks know and we'll make sure to update the ingest docs. Thanks!
Closes: #232
---
**Known issue in 8.8.0 and 8.8.1 Release Notes:**
**Resolution in 8.8.2 Release Notes:**
> Add known issue for Elastic Defend & Agent CPU spike bug

- docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
This adds the 8.10.4 Fleet & Agent Release Notes:
- Fleet contents are copied from the [Kibana RN PR](https://github.com/elastic/kibana/pull/168599)
- No Fleet Server contents according to [BC1 fragments](https://github.com/elastic/fleet-server/tree/adc11090b3559e32302606d8b8cb23802d64f309/changelog/fragments)
- Elastic Agent contents are from the [BC1 fragments](https://github.com/elastic/elastic-agent/tree/a92ca32b922dc62e45b532600a8562ee1c82205f/changelog/fragments) and [8.10.4 changelog PR](https://github.com/elastic/elastic-agent/pull/3606).
Closes: #595 
---
> Add Fleet & Agent 8.10.4 Release Notes

- docs/en/ingest-management/commands.asciidoc
Parameters for the Elastic Agent `ingest` and `enroll` commands are single sourced because the lists are identical. This will change with the `--base-path` parameter which applies to `install` only, so this PR splits the single-sourcing into two distinct lists. This will make it easier for others to contribute in future.
Rel: #600
> Un-single-source install and enroll command options

- docs/en/ingest-management/commands.asciidoc
I inadvertently included the `--base-path` option in https://github.com/elastic/ingest-docs/pull/601 so this removes it. I will re-add the option with the command description, etc. in a second PR.
> Remove base-path option, temporarily

- docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
This updates the [restart upgrade](https://www.elastic.co/guide/en/fleet/8.11/upgrade-elastic-agent.html#restart-upgrade-single) (single agent; multiple agent) docs sections, as shown below:
Closes: #605
This should go into 8.12 and higher.
> Document required cooldown between restart attempts

- docs/en/ingest-management/commands.asciidoc
Updates the [install command](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-install-command) docs page to include the new install `--base-path <string>` parameter.
Closes: https://github.com/elastic/ingest-docs/issues/600
---
> Add install '--base-path' parameter to agent command reference

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Version 8.11 now includes a restart upgrade feature, documented via #500. Based on discussion [here](https://github.com/elastic/ingest-docs/issues/605#issuecomment-1766834431), we should also remove the troubleshooting instructions for stuck agent upgrades, and instead point people to the new restart upgrade instructions
> Redirect troubleshooting for stuck agent upgrades

- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
Update the documentation to set the host as an optional hint. This follows the work in https://github.com/elastic/elastic-agent/pull/3575.
Relates to https://github.com/elastic/elastic-agent/pull/3575.
> [Hints Support] Update documentation for hints/host

- docs/en/ingest-management/elastic-agent/configuration/examples/config-file-example-apache.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/examples/config-file-examples.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/structure-config-file.asciidoc
- docs/en/ingest-management/index.asciidoc
This adds configuration examples for Apache logs and metrics. The intent is to add similar examples for the Nginx and System Integrations, so let's make sure the format for this one looks good and then I'll proceed with the other two.
[DOCS PREVIEW](https://ingest-docs_583.docs-preview.app.elstc.co/guide/en/fleet/master/config-file-examples.html) (follow the "Apache HTTP Server" link)
Closes: #584
> Add standalone agent config file example: Apache HTTP Server

- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc
Redo of https://github.com/elastic/ingest-docs/pull/620 targetting `main`.
> Fix code typo on Kubernetes autodiscover page

- docs/en/ingest-management/elastic-agent/configuration/examples/config-file-example-nginx.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/examples/config-file-examples.asciidoc
This adds configuration examples to ingest Nginx logs and metrics using standalone Elastic Agent. The example is similar to the [Apache examples](https://github.com/elastic/ingest-docs/pull/583) that were added very recently.
Closes: https://github.com/elastic/ingest-docs/issues/588
> Add standalone agent config file example: Nginx HTTP Server

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
- docs/en/ingest-management/integrations/install-integration-assets.asciidoc
- docs/en/ingest-management/integrations/view-integration-policies.asciidoc
The Integrations UI now has category filters, implemented by https://github.com/elastic/kibana/issues/147125
This adds a note in a few spots in the Fleet & Agent docs to mention that the full list of integrations can be filtered.
Closes: https://github.com/elastic/ingest-docs/issues/238
> Note that integrations list can be filtered by category

- docs/en/ingest-management/index.asciidoc
Based on [a couple of suggestions](https://github.com/elastic/ingest-docs/issues/638#issuecomment-1791978985), this:
- Moves the "data streams" section to be part of "Manage integrations".
- Moves the "Manage Elastic Agents in Fleet" and the "Configure standalone Elastic Agents" sections to be consecutive in the ToC.
The original structure, with data streams part of the "Manage Elastic Agents in Fleet" section, gives the impression that they're supported only with Fleet and not when standalone agents are used.
PREVIEW
---
> Move data streams into integrations section; reorder ToC

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This adds the 8.11.0 Fleet & Elastic Agent Release Notes:
- Fleet Server contents are from [BC9 fragments](https://github.com/elastic/fleet-server/tree/de43d84e257cd4d0ed1243e99d23dafefa46b176/changelog/fragments)
- Elastic Agent contents are from the [BC9 fragments](https://github.com/elastic/elastic-agent/tree/3c8be7201bbf4e3f91d7b56de9ff285c386a7804/changelog/fragments)
**NOTE:** For Fleet I've added a link to the [Kibana Release Notes](https://www.elastic.co/guide/en/kibana/master/release-notes.html). I think this makes more sense than duplicating the entries in the Kibana Guide and Fleet & Agent Guide, especially if edits to the entries in this PR aren't synced back with the Kibana release notes. Lately the entries have some differences between the two books and I think that could …
> Add Fleet & Agent 8.11.0 Release Notes

- docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Updates the macOS install path as shown:
> Fix agent install path for macOS

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/fleet/fleet-deployment-models.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/overview.asciidoc
- docs/en/ingest-management/serverless-restrictions.asciidoc
This PR:
- Enables the Serverless restrictions in the current (8.11) Fleet and Agent docs.
- On request from Josh, changes the number of supported Elastic Agents from 25,000 to 10,000.
---
[Install Elastic Agents](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html) (already published)
---
---
Fleet and Elastic Agent restrictions for Elastic Cloud serverless (will be published with this PR)
---
> Change Serverless agent restriction to 10 thousand installs

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/fleet/fleet.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/3183 by updating the Fleet & Elastic Agent guide with some notes and links regarding Elastic Defend's Agent tamper protection feature, which is configured and accessed via Agent policy and Fleet UI. Links to [Elastic Security docs](https://www.elastic.co/guide/en/security/master/agent-tamper-protection.html) created via https://github.com/elastic/security-docs/pull/4232.
Previews:
- [Uninstall Elastic Agents from edge hosts](https://ingest-docs_674.docs-preview.app.elstc.co/guide/en/fleet/master/uninstall-elastic-agent.html) — Added note below uninstall Agent commands.
- [Centrally manage Elastic Agents in Fleet](https://ingest-docs_674.docs-preview.app.elstc.co/guide/en/fleet/master/manage-agents-in-fleet.html) — Added …
> Update Fleet/Agent docs for Agent tamper protection (Elastic Defend)

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.15 Fleet & Agent Release Notes:
- Fleet: no RN entries in Kibana PR
- Fleet Server: No fragments in bc1
- Elastic Agent: No changelog file for bc1
---
> Add Fleet & Agent 7.17.15 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This adds the 8.11.0 Fleet & Elastic Agent Release Notes:
- Fleet contents are copied from the Kibana 8.11.1 RN PR: https://github.com/elastic/kibana/pull/171087
- No Fleet Server contents in [BC2 fragments](https://github.com/elastic/fleet-server/tree/8a5688dc81835c6924e9902da4275ca3d7a973e0/changelog/fragments)
- Elastic Agent contents are from the [BC2 fragments](https://github.com/elastic/elastic-agent/tree/03ef9d8d6a894af61a77d78983a735d263b414ac/changelog/fragments)
I've also updated the 8.11.0 Release Notes to include the items for Fleet. I originally had a link to the Kibana release notes, which include the Fleet updates, as an alternative to duplicating the entries in both sets of release notes. However, it's been reported that this isn't clear for our users.
---
> Add Fleet & Agent 8.11.1 Release Notes

- .github/CODEOWNERS
Updates CODEOWNERS to the larger @elastic/platform-docs team. This ensures there are reviewers around when folks are absent, etc.
> Change CODEOWNERS to platform-docs

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Adds workaround steps to address the known issue affecting Elastic Agent upgrades in 8.11.0 and 8.11.1.
Please see the [documentation preview](https://ingest-docs_687.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.11.0.html#known-issues-8.11.0).
Closes: #686
> Update 8.11.0 and 8.11.1 Release Notes with upgrade issue workaround

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
This updates the [Advanced YAML Configuration](https://www.elastic.co/guide/en/fleet/8.11/es-output-settings.html#es-output-settings-yaml-config) section of the Elasticsearch output settings page to include the `compression_level` setting (shown below), which previously was documented only in the section for standalone agent outputs.
Closes: https://github.com/elastic/platform-docs-team/issues/276
> Add compression_level setting to Fleet ES output page

- docs/en/ingest-management/data-streams.asciidoc
This adds docs for the new ingest pipeline extension points:
- Updates the "[Ingest pipelines](https://ingest-docs_675.docs-preview.app.elstc.co/guide/en/fleet/master/data-streams.html#data-streams-pipelines)" section with a description and example of each level of customization.
- Adds a new "[Step 6](https://ingest-docs_675.docs-preview.app.elstc.co/guide/en/fleet/master/data-streams-pipeline-tutorial.html#data-streams-pipeline-six)" to the ingest pipelines tutorial, showing how to process all log events.
Closes #638
Target: 8.12.0
@nchaulet and @kpollich I hope I've understood these extension points correctly. :-)
> Add docs for new ingest pipeline extension points in Fleet

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This updates the tip shown near the bottom of the [known issue](https://www.elastic.co/guide/en/fleet/current/release-notes-8.11.0.html#known-issues-8.11.0) affecting agent upgrades, included in the 8.11.0 and 8.11.1 Release Notes.
**original:**
**updated:**
> Update Agent ID tip in 8.11 upgrade known issue

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
This adds the steps to:
- Configure a remote Elasticsearch cluster as an Elastic Agent output
- Update an Elastic Agent policy to use the new remote cluster.
@juliaElastic Please let me know if I've missed anything.
Target: 8.12
Closes: #530
PREVIEW
- New section [Send Elastic Agent monitoring data to a remote Elasticsearch cluster](https://ingest-docs_700.docs-preview.app.elstc.co/guide/en/fleet/master/monitor-elastic-agent.html#external-elasticsearch-monitoring)
- A note at the top of the [Elasticsearch output settings](https://ingest-docs_700.docs-preview.app.elstc.co/guide/en/fleet/master/es-output-settings.html) page,
> Document sending agent monitoring data to a remote Elasticsearch clsuter

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Adds the known issue (fixed by https://github.com/elastic/elastic-agent-system-metrics/pull/115) to the 8.11.0 and 8.11.1 Release Notes.
@cmacknz @pierrehilbert Do you think there's any workaround guidance that we should add, other than just waiting for 8.11.2?
---
> Add known issue for PssFreeSnapshot memory leak

- docs/en/ingest-management/commands.asciidoc
This updates the [Elastic Agent command reference](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html) page to note that:
- The `--base-path` install option does not work with Elastic Defend. CC @joepeeples, we should both keep an eye on this restriction, so that we can update the docs if it eventually goes away.
- All of the commands can be applied to both Fleet-managed and standalone Elastic Agent.
Closes: #688 
---
---
> Update command reference docs

- docs/en/ingest-management/integrations/install-integration-assets.asciidoc
This just expands the warning about Spaces on the [Install and uninstall Elastic Agent integration assets](https://www.elastic.co/guide/en/fleet/master/install-uninstall-integration-assets.html) page.
Rel: #708
> Expand guidance for integrations and Kibana spaces

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This updates the [8.11.1 release notes](https://www.elastic.co/guide/en/fleet/current/release-notes-8.11.1.html) to correct the known upgrade issue (the issue affects both version 8.11.0 and 8.11.1).
> Update 8.11.1 Release Notes for upgrade issue

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This, recommended by Nima, adds a banner to the 8.11.0 and 8.11.1 release notes to call attention to the known issue affecting Windows systems.
> Add notice for Windows memory leak issue in 8.11.0 and 8.11.1 RN

- .github/workflows/docs-preview.yml
@nkammah Thanks for the explanation of how to add these previews!
I noticed that this line doesn't include any version branch (`current`, `main`, `8.11`), so I hope I've got things right: `preview-path: 'guide/en/fleet/index.html'`
Just for reference, this is a copy of https://github.com/elastic/elasticsearch-py/pull/2389
> Add GH action for posting docs preview

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.16 Fleet & Agent Release Notes:
Fleet: no RN entries in [Kibana PR](https://github.com/elastic/kibana/pull/172486)
Fleet Server: No fragments in [BC1](https://github.com/elastic/fleet-server/tree/9958b49002388ecd2323c057a6bfbc6638b3fd8d/changelog/fragment)
Elastic Agent: No changelog file in [BC1](https://staging.elastic.co/7.17.16-1d74549d/summary-7.17.16.html)
Rel: #733 
---
> Add Fleet & Agent 7.17.16 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This adds the 8.11.2 Fleet & Elastic Agent Release Notes:
- Fleet contents are copied from the [Kibana 8.11.1 Release Notes PR](https://github.com/elastic/kibana/pull/172583).
- Fleet Server: Nothing added since there are [no Fleet Server fragments in BC1](https://github.com/elastic/fleet-server/tree/6df48cbca66df891d7464b33e0d07808742b3439/changelog/fragment)
- Elastic Agent contents are from [Elastic Agent BC1 fragments](https://github.com/elastic/elastic-agent/tree/1c21b00aae80a638a00ae5f549fcbcca32890660/changelog/fragments)
See [DOCS PREVIEW](https://ingest-docs_731.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.11.2.html)
Closes: #733
> Add Fleet & Agent 8.11.2 Release Notes

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
This adds two new sections to the Fleet [Elasticsearch output settings](https://ingest-docs_749.docs-preview.app.elstc.co/guide/en/fleet/master/es-output-settings.html) docs page:
1. Description of the new "Performance tuning" option:
2. These two [Performance tuning settings](https://ingest-docs_749.docs-preview.app.elstc.co/guide/en/fleet/master/es-output-settings.html#es-output-settings-performance-tuning-settings) tables, one showing the settings and one showing the potential performance impact.
Closes: #720
> Document presets for performance tuning to ES output

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This updates the 8.11.0 and 8.11.1 Release Notes to indicate that the memory leak issue impacts all Beats running on these versions, rather than just Metricbeat.
It also fixes a small typo and removes the "upcoming" reference to version 8.11.2, since that version is now available.
---
> Update memory leak known issue to indicate all Beats are affected, updated workaround

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This updates the Fleet & Agent Install landing page and Command reference page to note that Windows Powershell ISE is not supported. It also reformats the restrictions on both pages into one large note, rather than separate notes.
Closes #267
---
---
> Add restriction that PowerShell ISE is not supported

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
This updates the tuning presets table to give a better indication of performance expectations.
Rel: #720
> Updating some of the data around the tuning presets

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Removes "Sending monitoring data to a remote Elasticsearch cluster is currently not supported." The feature is supported as of 8.12.0.
Rel: #530
> Remove external ES monitoring restriction

- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
This follows https://github.com/elastic/ingest-docs/pull/696 to add a setting that I missed in the first PR.
That first PR added notes that the following output settings can be stored as secrets:
- Kafka output password
- Kafka output SSL key
- Logstash output SSL key
This PR adds a similar note for the Remote Elasticsearch service token:
Rel: https://github.com/elastic/ingest-docs/issues/692
See [Preview page](https://ingest-docs_762.docs-preview.app.elstc.co/guide/en/fleet/master/monitor-elastic-agent.html#external-elasticsearch-monitoring)
---
> Document that remote ES service token can be stored as a secret

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
This adds docs for agent output secrets. 
@jillguyonnet This is definitely a "first draft". I'm not sure that I've got the "Policy secret values" section (down at the bottom) quite right. Please let me know what you think.
Target: 8.12
Rel: #692
Docs preview links:
- [Kafka authentication settings](https://ingest-docs_696.docs-preview.app.elstc.co/guide/en/fleet/master/kafka-output-settings.html#_authentication_settings)
- [Logstash output settings](https://ingest-docs_696.docs-preview.app.elstc.co/guide/en/fleet/master/ls-output-settings.html#ls-output-settings)
---
Update to Logstash and Kafka outputs pages:
> Docs for secrets storage in agent outputs

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Adds a title to our second Performance Tuning table in the Elasticsearch output docs.
> Add title to Performance Tuning EPS table

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Update release notes with the air-gapped upgrade issue and the latest version not available from Fleet
> Update release notes with upgrade issues

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
presets only apply to 8.12 and above agents.
@kilfoyle I am not sure if the version can be referenced this way or needs a variable.
> presets only apply to 8.12 and above agents

- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
This updates the Monitor Elastic Agents page with settings available in Fleet that can be used to trigger alerts, ML jobs, etc.
@nimarezainia, please let me know if there's anything you'd like changed.
Closes: #760
See changes in [DOCS PREVIEW](https://ingest-docs_763.docs-preview.app.elstc.co/guide/en/fleet/master/monitor-elastic-agent.html#fleet-alerting)
> Document Fleet alerting

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
action_limit was added as part of https://github.com/elastic/fleet-server/pull/2994 which i think made it into 8.12.0
policy_limit is a part of https://github.com/elastic/fleet-server/issues/3008 which is new
> Add missing action_limit settings and new policy_limit settings

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This updates the 8.11.2 Release Notes with the "latest version not available from Fleet" issue, which was also added to 8.11.3 via https://github.com/elastic/ingest-docs/pull/775. This way, all affected 8.11.x versions are consistent.
> Update 8.11.2 release notes with Fleet UI upgrade issue

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
I think we should mention how the data is flowing. Otherwise it can be confusing. How will be the elastic agent diagnostics be retrieved, if no Elasticsearch output is defined because logstash is used.
Maybe we can add a simplified version of the flow chart: https://user-images.githubusercontent.com/6766512/190254026-75cc900f-08c6-48c7-8789-56bd8304d933.png  from https://github.com/elastic/ingest-dev/issues/1224
thanks to @ckauf for digging the things up.
> Add information about elastic agent diagnostics flow

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
Users sometimes run the agent uninstall command from the wrong location, causing instability, so we need clear warnings in the docs.
Closes: #795 
---
**Update to agent [uninstall instructions](https://www.elastic.co/guide/en/fleet/current/uninstall-elastic-agent.html#uninstall-elastic-agent):**
---
**Update to the agent [`uninstall` command](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-uninstall-command):**
> Improve agent uninstall docs to ensure correct directory

- docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
This adds the 8.11.4 Fleet & Elastic Agent Release Notes:
- Fleet: no items in the [Kibana 8.11.4 Release Notes PR](https://github.com/elastic/kibana/pull/174636)
- Fleet Server: [no fragments for 8.11.4 BC1](https://github.com/elastic/fleet-server/tree/b154b29c1744825e9295ea6fea63a3d2a3b70c67/changelog/fragment)
- Elastic Agent: [fragments for 8.11.4 BC1](https://github.com/elastic/elastic-agent/tree/dccb92bd414e420df6844fcd477077bda349b55f/changelog/fragments)
---
> Add Fleet & Agent 8.11.4 Release Notes

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This updates the Fleet & Agent [Troubleshooting page](https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html) with an entry for the "Runtime fields cannot be used in TSDB indices" issue described in this [innovation hub](https://support.elastic.dev/knowledge/view/9363b9fd) article.
Closes: https://github.com/elastic/ingest-docs/issues/808
> Add troubleshooting for TSDB runtime issue

- docs/en/ingest-management/fleet/air-gapped.asciidoc
This adds a section on the [Air-gapped environments](https://www.elastic.co/guide/en/fleet/current/air-gapped.html) page about the new `isAirGapped` flag in Fleet, added in 8.13.
Closes: #790
> Document Fleet isAirGapped setting

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This removes restrictions that are documented twice on the [Install Elastic Agents](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html#elastic-agent-installation) page.
> Remove duplicate restrictions from agent install page

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This adds the 8.12.0 Fleet & Elastic Agent Release Notes:
- Fleet contents from [Kibana 8.12.0 Release Notes PR](https://github.com/elastic/kibana/pull/174429)
- Fleet Server contents from [BC6 changelog](https://github.com/elastic/fleet-server/tree/174e54833c59faf1e70a5a38928d6314ba63c55f/changelog/fragment) - No fragments!
- Elastic Agent from [BC6 changelog](https://github.com/elastic/elastic-agent/tree/a9742cbf93b30dd92b13d2573ff84c5bad31cf88/changelog/fragments)
See [DOCS PREVIEW](https://ingest-docs_773.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.12.0.html)
Closes: #772
---
**Edit:** Updated with the agent enroll command known issue:
> Add Fleet & Agent 8.12.0 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Add a link directly to the agent upgrade details docs. Got some user feedback that this change should be more obvious in the release notes, this is my attempt to do that.
> Make the agent upgrade tracking change more obvious and link directly to the docs

- docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc
- fix namespace fields
- add information about the deployment and cronjob settings in add_resource_metadata
> Fix kubernetes provider documentation

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This adds steps to the [Troubleshooting](https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html) page to resolve when a Fleet Server integration has been removed from an agent policy.
(I also included a super small change to fix a code example in a previous troubleshooting item.)
Closes: #745
PREVIEW
> Add troubleshooting note for removed Fleet Server integration

- docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
This updates the [Elastic Agent upgrade page](https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html) with a link to this [Communications amongst components](https://github.com/elastic/elastic-agent/blob/main/docs/upgrades.md) diagram, detailing the Elastic Agent upgrade process.
We decided that providing a link is more effective than rendering a graphic, since the latter would be more difficult to maintain as the process changes.
Closes: #823
> Add link to 'communications amongst components' diagram

- docs/en/ingest-management/data-streams.asciidoc
With https://github.com/elastic/kibana/pull/174776, agent policy namespaces will now cascade to integration policies unless otherwise specified. This adds a paragraph to clarify that behaviour in the docs:
> Add details about agent namespaces cascading to integration policies

- docs/en/ingest-management/commands.asciidoc
Add new mTLS flags for 8.13 introduced in https://github.com/elastic/elastic-agent/pull/4007
> Add agent mTLS flags

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.17 Fleet & Agent Release Notes:
Fleet: no RN entries in [Kibana PR](https://github.com/elastic/kibana/pull/175111)
Fleet Server: No fragments in [BC1](https://github.com/elastic/fleet-server/tree/a9434fe27468a5e429909bc632cd35f755e4e282/changelog/fragment)
Elastic Agent: No changelog file in [BC1](https://staging.elastic.co/7.17.17-6a0f933a/summary-7.17.17.html)
---
> Add Fleet & Agent 7.17.17 Release Notes

- docs/en/ingest-management/data-streams.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This updates the [ingest pipelines](https://www.elastic.co/guide/en/fleet/current/data-streams.html#data-streams-pipelines) section of the docs as well as the Release Notes, to warn about possible naming collisions with the new custom ingest pipelines. 
Closes: #841
@kpollich I'm not sure if I've understood or explained this very well, so I'd appreciate if you can add any changes you think we need. Thanks!
---
**Release Notes "New features" update**
---
**Release Notes "Breaking changes" update**
---
**Data Streams page update**
> Document possible collisions with '@custom ingest pipelines'

- docs/en/ingest-management/fleet/fleet-settings-remote-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
Previously, the steps to configure a remote Elasticsearch output were documented in the "Agent Monitoring" section of the docs, since I thought only monitoring data was supported.
Since both integrations and monitoring data are now supported, I've made a new Remote Elasticsearch Output page.
Please see previews:
- New [Remote Elasticsearch Output](https://ingest-docs_850.docs-preview.app.elstc.co/guide/en/fleet/master/remote-elasticsearch-output.html) page
- Updated [Send Elastic Agent monitoring data to a remote Elasticsearch cluster](https://ingest-docs_850.docs-preview.app.elstc.co/guide/en/fleet/master/monitor-elastic-agent.html#external-elasticsearch-monitoring) section
Closes: https://github.com/elastic/ingest-docs/issues/848
Closes: #759
> Add docs to configure remote ES output

- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
This adds a paragraph to the [Logstash output settings](https://www.elastic.co/guide/en/fleet/8.12/ls-output-settings.html) section ~~and the [Send Elastic Agent monitoring data to a remote Elasticsearch cluster](https://www.elastic.co/guide/en/fleet/8.12/monitor-elastic-agent.html#external-elasticsearch-monitoring) section of the docs~~ instructing people to "prepare" the remote cluster by installing integration assets for any integrations added to the agent policy.
Edit: To avoid a merge conflict the remove ES change will instead be added via https://github.com/elastic/ingest-docs/pull/850
Closes: #845 
---
Added to the configure remote Elasticsearch steps:
---
Added to the Logstash output docs:
> Add instructions to prepare remote clusters with integration assets

- docs/en/ingest-management/data-streams.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This updates the 8.12.0 Release Notes breaking change for ingest pipelines, with the details from https://github.com/elastic/ingest-docs/issues/841
@kpollich I omitted the screen capture since we normally don't have those in the release notes, and I'm reluctant to add one while we're considering moving those pages to an auto-generated format.
I've also added a note to the [Ingest pipelines](https://www.elastic.co/guide/en/fleet/current/data-streams.html#data-streams-pipelines) docs section referring users to the breaking changes item for details.
Closes: #841
---
**PREVIEW**
> Update breaking change for pipelines

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This updates the Fleet & Agent [Troubleshooting page](https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html) with a description of how to detect and resolve OOM errors on Kubernetes.
Closes #839
---
PREVIEW
> Add troubleshooting for Agent Out of Memory on K8s

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
Luca rightly points out that the [Fleet UI settings](https://www.elastic.co/guide/en/fleet/current/fleet-settings.html) section title is a bit misleading, so this fixes that problem.
> Update title for Fleet settings section

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-shared-settings.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
This adds the memory queue configuration settings to the standalone Elastic Agent output docs (for Elasticsearch and Logstash outputs) and the Fleet-managed Elastic Agent output docs (for Elasticsearch, Logstash, and Kafka outputs).
Note: The memory queue configuration settings for standalone Elastic Agent's Kafka output will be added separately, as part of https://github.com/elastic/ingest-docs/issues/637
Please see [PREVIEW](https://ingest-docs_bk_859.docs-preview.app.elstc.co/guide/en/fleet/master/logstash-output.html#output-logstash-memory-queue-settings) (example from the standalone agent Logstash output settings)
Closes: #526
> Document memory queue configuration

- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Adds a known issue for the AWS S3 performance regression described in https://github.com/elastic/beats/issues/37754
- Beats port of this know issue is in https://github.com/elastic/beats/pull/37766
> Add known issue for AWS S3 performance regression in 8.12

- docs/en/ingest-management/commands.asciidoc
This adds options that were missing in the docs for the Elastic Agent `enroll` and `install` commands. Options have been confirmed using `sudo elastic-agent install -h` and `sudo elastic-agent enroll -h` in an 8.12 image. This also re-orders a few items to be alphabetical.
__DOCS PREVIEW__
- [elastic-agent enroll](https://ingest-docs_bk_860.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-cmd-options.html#elastic-agent-enroll-command)
- [elastic-agent install](https://ingest-docs_bk_860.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-cmd-options.html#elastic-agent-install-command)
__ADDITIONS__
`enroll` command:
--daemon-timeout
--fleet-server-timeout
--header
--proxy-disabled
--proxy-header
--proxy-url
--staging
`install` command:
--daemon-timeout …
> Add missing options for Elastic Agent 'enroll' and 'install' commands

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
The setting descriptions are based off of the [Beats Kafka output settings](https://www.elastic.co/guide/en/beats/filebeat/current/kafka-output.html#topics-option-kafka) and the [Fleet-managed agent Kafka output settings](http://localhost:8000/guide/kafka-output-settings.html#_general_settings) (we updated some of the Kafka output settings descriptions when the settings were made available in Fleet).
Please see [DOCS PREVIEW TBD]()
Closes: #637
> Add Kafka output settings to standalone agent docs

- docs/en/ingest-management/fleet-agent-proxy-package-registry.asciidoc
This adds the following to the [Set the proxy URL of the Elastic Package Registry](https://www.elastic.co/guide/en/fleet/current/epr-proxy-setting.html) page.
Closes: https://github.com/elastic/ingest-docs/issues/873
---
> Add details about info shared, via proxy, with the EPR

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.18 Fleet & Agent Release Notes:
Fleet: no RN entries in [Kibana PR](https://github.com/elastic/kibana/pull/176216)
Fleet Server: No fragments in [BC1](https://github.com/elastic/fleet-server/tree/595e77811fc27d53c095478c6bf7d0ed58433e67/changelog/fragment)
Elastic Agent: No changelog file in [BC1](https://staging.elastic.co/7.17.18-bdb3703e/summary-7.17.18.html)
---
> Add Fleet & Agent 7.17.18 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This adds the 8.12.1 Fleet & Elastic Agent Release Notes:
- Fleet contents from [Kibana 8.12.1 Release Notes PR](https://github.com/elastic/kibana/pull/176214)
- Fleet Server contents from [BC1 changelog](https://github.com/elastic/fleet-server/tree/174e54833c59faf1e70a5a38928d6314ba63c55f/changelog/fragment) - No fragments!
- Elastic Agent from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/9db5527750c7b3510cbedca152590c24444eba2b/changelog/fragments)
This includes the breaking change "Naming collisions with Fleet custom ingest pipelines".
See [DOCS PREVIEW](https://ingest-docs_bk_864.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.12.1.html)
Closes: #861
Closes: #885
> Add Fleet & Agent 8.12.1 Release Notes

- docs/en/ingest-management/data-streams.asciidoc
Note to self: Wait for 8.12.1 to merge.
This updates the "ingest pipelines" section of the data streams docs page to indicate the new naming pattern for custom integrations pipelines.
See [DOCS PREVIEW](https://ingest-docs_bk_863.docs-preview.app.elstc.co/guide/en/fleet/master/data-streams.html#data-streams-pipelines).
Rel: #861 
---
> Update ingest pipeline docs with new integrations pattern naming

- docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
This will backport the following commits from `main` to `8.10`:
- [Adds tip about creating Elastic Defend policy using Fleet API (#417)](https://github.com/elastic/ingest-docs/pull/417)
> [8.10] Adds tip about creating Elastic Defend policy using Fleet API (#417)

- docs/en/ingest-management/serverless-restrictions.asciidoc
Agent and Fleet Server proxies are now supported on serverless. This updates the [serverless restrictions](https://www.elastic.co/guide/en/fleet/current/fleet-agent-serverless-restrictions.html) page to clarify the current limitations.
@jillguyonnet Thanks for the super clear issue! Please let me know if I've missed anything. One small thing I wonder is if "Outputs" should maybe be "Elastic Agent outputs", or instead maybe just a sub-heading of the "Elastic Agent" section.
Closes: https://github.com/elastic/ingest-docs/issues/887
---
> Update serverless restrictions wrt proxy support

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
This removes the `policy_limit` settings from 8.13, from which they'll likely be pulled, and from 8.12 where they were never added.
> Remove Fleet Server policy_limit settings

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
The Fleet & Agent troubleshooting page is growing and has become difficult to navigate. This adds a ToC at the top to help users find the articles they need more easily.
Closes: #898
---
> Add ToC to troubleshooting docs

- docs/en/ingest-management/integrations/install-integration-assets.asciidoc
This adds detail to the integrations assets docs, including links to a known issue and a discussion issue. It also puts the content in an "Important" block to make it more prominent.
Docs [preview page](https://ingest-docs_894.docs-preview.app.elstc.co/guide/en/fleet/master/install-uninstall-integration-assets.html)
Closes: https://github.com/elastic/ingest-docs/issues/881
---
> Expand and make more prominent integrations multi-space limitations

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
This updates the standalone agent docs to explain the new `presets` option for Elasticsearch output.
Docs [preview](https://ingest-docs_896.docs-preview.app.elstc.co/guide/en/fleet/master/elasticsearch-output.html#output-elasticsearch-performance-tuning-settings)
Closes: #879
**Updated "Performance tuning settings" summary:**
**New entry for the `preset` option:**
> Add performance tuning presets to standalone agent docs

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This update the Fleet & Agent troubleshooting docs with a workaround for when an agent can't be unenrolled in Fleet because the agent policy has been deleted.
Closes: #897
See [docs preview](https://ingest-docs_903.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-troubleshooting.html#deleted-policy-unenroll)
---
> Add troubleshooting for agent that can't be unenrolled

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Merge after https://github.com/elastic/fleet-server/pull/3255
https://github.com/elastic/ingest-docs/pull/892 removed the `policy_limit` settings which are being replaced by (re) using the `action_limit` settings in the above PR
> Deprecate the fleet-server policy_throttle, use action_limit instead.

- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This adds a known issue for the stuck agent upgrades to the 8.12.0 and 8.12.1 Release Notes.
Thanks @julia for the really clear explanation!
Closes: #907
---
> Add known issue for stuck agent upgrade (8.12.0, 8.12.1)

- docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
This updates the [Grant standalone Elastic Agents access to Elasticsearch](http://localhost:8000/guide/grant-access-to-elasticsearch.html) page:
- Indicate that API key authentication is required for serverless.
- Correct the API key format description (delimiter is `:` rather than `.`).
- Provide the Kibana path for serverless, since it's different from the on-prem and ESS versions (I confirmed that the path is `Project settings -> Management -> API keys` in the Obs, Sec, and Elasticsearch projects).
Apart from the above, the docs seem to be nicely up to date.
Closes: #697
> Small fixes for API keys docs

- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This will backport the following commits from `main` to `8.12`:
- [Add known issue for stuck agent upgrade (8.12.0, 8.12.1) (#908)](https://github.com/elastic/ingest-docs/pull/908)
> [8.12] Add known issue for stuck agent upgrade (8.12.0, 8.12.1) (#908)

- docs/en/ingest-management/security/logstash-certificates.asciidoc
`ssl` and `ssl_verify_mode` settings are deprecated for the Elastic Agent input (Logstash).
I adjusted the examples with current valid settings: `ssl_enabled` and `ssl_client_authentication` based of latest Logstash documentation: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-elastic_agent.html#plugins-inputs-elastic_agent-ssl_client_authentication
> [DOCS] Fix Elastic Agent input examples

- docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
- docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-serverless.asciidoc
- docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx.asciidoc
- docs/en/ingest-management/index.asciidoc
This adds a new serverless version of the tutorial [Use standalone Elastic Agent with Elasticsearch Service to monitor nginx](https://www.elastic.co/guide/en/fleet/current/example-standalone-monitor-nginx.html).
For the new guide, all of the steps have been tested on a serverless project and modified accordingly.
A few things have also been fixed up in the original guide, most notably the switch to use API key authentication, as required on serverless and as recommended on stateless.
Closes: #904
Rel: #693
> Add tutorial for standalone agent on serverless monitoring nginx

- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
in #908 I fixed the "stuck upgrade" known issue for 8.12.0 only, and forgot about 8.12.1. So this fixes that omission.
Also, I've added `After running these API requests, wait at least 10 minutes, and then the agents should be upgradeable again.` at the end of the workaround steps.
---
> Fix known issue for stuck upgrade in 8.12.1 release notes

- docs/en/ingest-management/fleet/migrate-elastic-agent.asciidoc
This fixes a few things in the "Reset the Elastic Cloud policy" section of the page [Migrate Fleet-managed Elastic Agents from one cluster to another](https://www.elastic.co/guide/en/fleet/current/migrate-elastic-agent.html), as suggested in https://github.com/elastic/ingest-docs/issues/922
Closes: #922 
---
> Fix migrate integrations docs

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
- docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
This makes a few small touch-ups to indicate that API key authentication is required on serverless, and generally recommended over basic auth. For the changes to the "debugging" example, I tested an agent policy and the resulting output from the `elastic-agent inspect` command to make sure that the updated formatting is correct.
I've also updated the API key generation to note that the UI path is slightly different in a serverless project.
The examples in the nginx monitoring tutorials were fixed separately.
Closes: #693
> Fix examples to use API key authentication

- docs/en/ingest-management/beats-agent-comparison.asciidoc
This PR documents explicitly that users cannot configure internal _disk_ queues for Agent-managed Beats in [this table](https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html#supported-configurations) comparing configurations supported by Beats vs. Agent.
> Document that disk queues cannot be configured for Agent-managed Beats

- docs/en/ingest-management/commands.asciidoc
The synopsis for the enroll command listed `--non-interactive`, which is an option on the install command and doesn't apply to enroll.
> Remove nonexistent option from enroll command

- docs/en/ingest-management/commands.asciidoc
This will backport the following commits from `8.12` to `8.13`:
- [Remove nonexistent option from enroll command (#930)](https://github.com/elastic/ingest-docs/pull/930)
> [8.13] Remove nonexistent option from enroll command (#930)

- docs/en/ingest-management/commands.asciidoc
This will backport the following commits from `8.12` to `main`:
- [Remove nonexistent option from enroll command (#930)](https://github.com/elastic/ingest-docs/pull/930)
> [main] Remove nonexistent option from enroll command (#930)

- docs/en/ingest-management/fleet/air-gapped.asciidoc
This will backport the following commits from `8.12` to `8.13`:
- [Update air-gapped.asciidoc (#934)](https://github.com/elastic/ingest-docs/pull/934)
> [8.13] Update air-gapped.asciidoc (#934)

- docs/en/ingest-management/fleet/air-gapped.asciidoc
This will backport the following commits from `8.12` to `main`:
- [Update air-gapped.asciidoc (#934)](https://github.com/elastic/ingest-docs/pull/934)
> [main] Update air-gapped.asciidoc (#934)

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
This commit updates the documentation from the Kafka output on standalone Elastic-Agent settings by removing the options that are not supported any more.
> Update Elastic-Agent Kafka settings

- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
This removes the "[Processors](https://www.elastic.co/guide/en/fleet/current/kafka-output-settings.html#_topics_settings)" section from the Kafka output for Fleet-managed Elastic Agent docs. The processors are no longer supported in Fleet, starting in 8.14, via https://github.com/elastic/kibana/pull/177229
Closes: #942
PREVIEW:
---
> Remove processors settings from Kafka output docs

- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This adds the 8.12.2 Fleet & Elastic Agent Release Notes:
- Fleet contents from [Kibana 8.12.2 Release Notes PR](https://github.com/elastic/kibana/pull/177335)
- Fleet Server contents from [BC1 changelog](https://github.com/elastic/fleet-server/tree/fa3452c5098931862a31be39051faf11dbc22740/changelog/fragments)
- Elastic Agent contents from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/de80b0d70174ba45dc869fdf121109763bbfcce0/changelog/fragments)
See [DOCS PREVIEW](https://ingest-docs_bk_939.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.12.2.html)
Rel: #933
> Add Fleet & Agent 8.12.2 Release Notes

- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
This will backport the following commits from `8.12` to `main`:
- [Update fleet-settings-output-kafka.asciidoc (#953)](https://github.com/elastic/ingest-docs/pull/953)
> [main] Update fleet-settings-output-kafka.asciidoc (#953)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/override-policy-settings.asciidoc
As requested in #954, this adds examples of agent policy overrides. I've included the warning proposed by Luca [here](https://github.com/elastic/kibana/issues/158699#issuecomment-1588945313), that it's possible for a custom configuration to break things.
Please see [docs preview page](https://ingest-docs_bk_962.docs-preview.app.elstc.co/guide/en/fleet/master/enable-custom-policy-settings.html)
Closes: #954
> Add custom settings page

- docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
This updates the [Upgrade Fleet-managed Elastic Agents](https://www.elastic.co/guide/en/fleet/master/upgrade-elastic-agent.html) page with a few restrictions about when upgrades are eligible.
@criamico Please let me know if if I've missed anything.
Closes: #966
> Add restrictions to agent upgrade docs

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/beats-agent-comparison.asciidoc
- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/inputs/simplified-input-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/installation-layout.asciidoc
- docs/en/ingest-management/elastic-agent/start-stop-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
- docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This removes most of the book-level attributes in the Fleet & Agent guide. I'm leaving a few that have to do with the tab widgets, so for those I'll wait and see how the Observability folks fix things up.
Backporting this to 8.13 so that if I've broken anything we'll know sooner rather than later.
Closes: #974
> Scrub book-level attributes from Fleet & Agent guide

- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Issue reported via Slack. The extra spaces cause the values not to be applied.
Note that the processors docs have been removed in later versions via https://github.com/elastic/ingest-docs/pull/943
> Remove key:value spaces from Kafka processors doc

- docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
This will backport the following commits from `main` to `8.12`:
- [Update scaling-on-kubernetes.asciidoc (#977)](https://github.com/elastic/ingest-docs/pull/977)
> [8.12] Update scaling-on-kubernetes.asciidoc (#977)

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.19 Fleet & Agent Release Notes:
Fleet: no RN entries in [Kibana PR](https://github.com/elastic/kibana/pull/179217)
Fleet Server: No fragments in [BC1](https://github.com/elastic/fleet-server/tree/146741d17e3fc07c52092c7a83fa7997936656e8/changelog/fragments)
Elastic Agent: No changelog file in [BC1](https://staging.elastic.co/7.17.19-cc2108c6/summary-7.17.19.html)
---
> Add Fleet & Agent 7.17.19 Release Notes

- docs/en/ingest-management/create-agent-policies-no-UI.asciidoc
Resolve https://github.com/elastic/kibana/issues/159444
Add variable to the preconfiguration example
> [Fleet] Add variable to the preconfiguration example

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-shared-settings.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
Bring over two relevant output changes from Beats.
Also sync the queue.flush.min_events documentation from Beats so that it is up to date with the most recent changes.
> Update 8.13.0 queue documentation and release notes

- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
The Kafka output type GAed in 8.13 so this removes the tech preview notice from the associated docs.
> Remove tech preview notice from Kafka output docs

- docs/en/ingest-management/data-streams.asciidoc
This adds Step 2, which was missing.
> Add missing step to edit integration policy namespace

- docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
This adds the 8.13.1 Fleet & Elastic Agent Release Notes:
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/179760)
* Fleet Server contents from [BC1 changelog](https://github.com/elastic/fleet-server/tree/3824b898d1e0a92d12e76f311cd3e9e0b08560e5/changelog/fragments) (No new entries)
* Elastic Agent contents from:
* [BC1 "core" changelog](https://github.com/elastic/elastic-agent/tree/818d20468f031265ad7415ef5567b934ffff35c0/changelog/fragments) (No new entries)
* [BC1 "package" changelog](https://github.com/elastic/elastic-agent/tree/1eb18c5ef69be30641aa415f9e40fabd38d2e4ad/changelog/fragments) (No new entries)
See [docs preview](https://ingest-docs_bk_992.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.13.1.html)
Closes: #991
> Add Fleet & Agent 8.13.1 Release Notes

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/data-streams.asciidoc
- docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
- docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
- docs/en/ingest-management/fleet-agent-proxy-managed.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
- docs/en/ingest-management/fleet/air-gapped.asciidoc
- docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-remote-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
- docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
- docs/en/ingest-management/integrations/install-integration-assets.asciidoc
- docs/en/ingest-management/integrations/integrations.asciidoc
- docs/en/ingest-management/integrations/upgrade-integration.asciidoc
- docs/en/ingest-management/integrations/view-integration-assets.asciidoc
- docs/en/ingest-management/integrations/view-integration-policies.asciidoc
- docs/en/ingest-management/migrate-beats-to-agent.asciidoc
- docs/en/ingest-management/serverless-restrictions.asciidoc
- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
The path to Fleet is different between hosted and serverless, and on serverless between Observability and Security deployments, so we'll update the path to simply "Open Fleet" or "In Fleet, ...".
This also makes a note of the different paths on the [serverless restrictions](https://www.elastic.co/guide/en/fleet/current/fleet-agent-serverless-restrictions.html) page:
Closes: #989
> Simplify step to open Fleet for compatibility with Serverless

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Preview: https://ingest-docs_bk_1006.docs-preview.app.elstc.co/guide/en/fleet/7.17/release-notes-7.17.20.html
> Added fleet-server known issue 7.17.20

- docs/en/ingest-management/overview.asciidoc
This advertises the more general and very helpful [Adding data to Elasticsearch](https://www.elastic.co/guide/en/cloud/current/ec-cloud-ingest-data.html) page from the Fleet & Agent overview.
Rel: https://github.com/elastic/platform-docs-team/issues/329
> Update overview with link to general Adding Data to ES docs

- docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
Requested by Nima, this adds an important known issue to the 8.13.0, 8.13.1, and 8.13.2 Release Notes.
> Add known issue for MSI binary installs

- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This is the same as https://github.com/elastic/ingest-docs/pull/1028, targetting the 8.12.2 Release Notes.
> Update 8.12.2 release notes for MSI slash issue

- docs/en/ingest-management/fleet/fleet-server-multiple-hosts.asciidoc
- docs/en/ingest-management/index.asciidoc
This adds a page explaining Fleet Servers behavior for supporting multiple Elasticsearch hosts.
Closes #1033
@michel-laterman Here's a [docs preview](https://ingest-docs_bk_1034.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-server-multiple-hosts.html). I tried to rephrase things a bit so please let me know if I misunderstood anything.
> Add docs for Fleet Server with multiple ES hosts

- docs/en/ingest-management/elastic-agent/install-agent-msi.asciidoc
- docs/en/ingest-management/index.asciidoc
Adds docs for installing Elastic Agent via the newly supported MSI packages, which will GA in 8.14.
Thanks for the nice draft, Amit! Please see [PREVIEW PAGE](https://ingest-docs_bk_1039.docs-preview.app.elstc.co/guide/en/fleet/master/install-agent-msi.html)
Closes: #1036
> Add docs for MSI install

- docs/en/ingest-management/fleet/fleet-settings-changing-outputs.asciidoc
- docs/en/ingest-management/index.asciidoc
@asmith-elastic Thanks a lot for putting so much detail into the issue. It helped a lot!
Please have a look and let me know if things are okay.
Preview:
---
Closes: #1035
> Add considerations for changing outputs in a policy

- docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
This fixes an issue reported in the docs feedback spreadsheet, specifically that we refer to a setting on the "Agents" tab that is actually on the "Agent policies" tab.
> Fix incorrect 'Agents tab' reference in Fleet Server setup

- docs/en/ingest-management/security/certificates.asciidoc
Some customers use network shares for storing certificates which leads to Elastic Agent service failing to run on OS startup.
> Add warning about storing certificates not locally

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.21 Fleet & Agent Release Notes:
- Fleet: no entries in [Kibana RN PR](https://github.com/elastic/kibana/pull/182258)
- Fleet Server: [No new fragments](https://github.com/elastic/fleet-server/tree/1de2432998bbfc96e98bc23fbfb72694d02f4829/changelog/fragments) in BC1
- Elastic Agent: no fragments in
- [agent core BC1](https://github.com/elastic/elastic-agent/tree/0c3ad3aafa4dc7482cd2fd568445cbe6cf6643fe/changelog/fragments)
- [agent package BC1](https://github.com/elastic/elastic-agent/tree/0c3ad3aafa4dc7482cd2fd568445cbe6cf6643fe/changelog/fragments)
Rel: https://github.com/elastic/ingest-docs/issues/1047
Here's the [link](https://www.elastic.co/guide/en/fleet/7.17/release-notes-7.17.20.html#known-issues-7.17.20) to the known issue that indicated as being fixed in this …
> Add Fleet & Agent 7.17.21 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
This adds the 8.13.3 Fleet & Elastic Agent Release Notes:
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/182254)
* Fleet Server contents from [BC1 changelog](https://github.com/elastic/fleet-server/tree/43a5ff9822f3943c3c4feb07ff19c738bf8c8b5a/changelog/fragments) (No new entries)
* Elastic Agent contents from:
* [BC1 "core" changelog](https://github.com/elastic/elastic-agent/tree/fe984fda6347991e6fe684b1c5c8821578842401/changelog/fragments)
* [BC1 "package" changelog](https://github.com/elastic/elastic-agent/tree/fe984fda6347991e6fe684b1c5c8821578842401/changelog/fragments)
Closes: #1047
PREVIEW
---
> Add Fleet & Agent 8.13.3 Release Notes

- docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
This adds some text to make clear that when upgrading Elastic Agent(s) any agent acting as Fleet Server should be upgraded first.
> Clarify that Fleet Server should upgraded before other agents

- docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
This adds the 8.13.4 Fleet & Elastic Agent Release Notes. There are no entries needed for this small patch release.
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/182795) (No entries)
* Fleet Server contents from [BC1 changelog](https://github.com/elastic/fleet-server/tree/46b4306a845f41844435c3a36fab02aeeebad4ee/changelog/fragments) (No new entries)
* Elastic Agent contents from [BC1 "core" changelog](https://github.com/elastic/elastic-agent/tree/a2e31a1c99df431b43ee5058b2e603eeba5e0421/changelog/fragments) (No new entries)
PREVIEW
---
> Add Fleet & Agent 8.13.4 Release Notes

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
This updates the two Logstash output settings pages (one for standalone agent and one for Fleet-manged agent) to provide more detail on the `loadbalance` setting.
To preview changes, see the `loadbalance` setting [here](https://ingest-docs_bk_1024.docs-preview.app.elstc.co/guide/en/fleet/master/ls-output-settings.html).
Details are from the discussion in `https://github.com/elastic/beats/issues/12567`.
Closes: #1023
> Add details on load balance behaviour with Logstash output

- docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
It's been suggested that we include a "Notable changes" section in the Fleet & Agent release notes for cases when non-breaking changes are added. This would match a recent, similar change to the [Elasticsearch release notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.13.0.html#notable-changes-8.13.0). 
This new section should be included only if we have an item that falls into it, as in the case of the ECS item as shown below. Our change log entries don't have a category for this type of change, so the writer (usually me) will need to try and catch items in this category.
> Move ECS note to new 'Notable changes' section in 8.13 RN

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/override-policy-settings.asciidoc
This updates the [Elastic Agent policies](https://www.elastic.co/guide/en/fleet/current/agent-policy.html) docs page with three settings added to the Fleet UI for 8.15:
- Limit CPU usage
- Agent HTTP monitoring
- Agent logging level
@jen-huang and @juliaElastic This also removes the `Maximum CPU usage` and `HTTP monitoring endpoint` settings from the [Enable custom settings in an agent policy](https://www.elastic.co/guide/en/fleet/current/enable-custom-policy-settings.html) page. To avoid any broken links from the UI (and the Kibana CI link checker complaining), can you please update the UI "Learn more" links for these three settings to these URLs:
```
https://www.elastic.co/guide/en/fleet/current/agent-policy.html#agent-policy-limit-cpu …
```
> Add new policy settings available in Fleet

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This adds the new Elastic Agent binary sizes for 8.13 and 8.14, and reorganizes the "[Minimum requirements](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html#_minimum_requirements)" section of the install docs slightly, as shown below.
Closes: #1088
---
> Add new agent disk size, plus some reorg of the requirements section

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
This adds the 8.14.0 Fleet & Elastic Agent Release Notes:
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/183914)
* Fleet Server contents from [BC5 changelog](https://github.com/elastic/fleet-server/tree/06101c8732535c666358679ad12185d2bbb11392/changelog/fragments)
* Elastic Agent contents from [BC5 "core" changelog](https://github.com/elastic/elastic-agent/tree/53ce8888909e9abe2a00da45d7e275a10fabc8a6/changelog/fragments)
See [DOCS PREVIEW](https://ingest-docs_bk_1079.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.14.0.html)
Closes: #1078
> Add Fleet & Agent 8.14.0 Release Notes

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
- docs/en/ingest-management/fleet/fleet-settings.asciidoc
This removes the "Technical Preview" warning that appears in a couple of spots in the docs for the FQDN feature.
Target: 8.15
Rel: https://github.com/elastic/ingest-dev/issues/3368#issuecomment-2145248184
> Remove 'technical preview' warning from FQDN docs

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
This updates the "[Configure monitoring for standalone Elastic Agents](https://www.elastic.co/guide/en/fleet/8.13/elastic-agent-monitoring-configuration.html)" docs page to include mention of the `/liveness` endpoint added for 8.15. Rel: https://github.com/elastic/elastic-agent/issues/107#issuecomment-2133910470
**ADD:** Please see my [comment below](https://github.com/elastic/ingest-docs/pull/1090#issuecomment-2136026119) for an additional change to the Fleet-managed agent docs.
---
> Add note about '/liveness' endpoint for standalone agent

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
This is a follow-on to https://github.com/elastic/ingest-docs/pull/1090 to fix the Fleet & Agent docs with respect to the new `/liveness` endpoint:
- Corrects the setting name to be `agent.monitoring.enabled.http` (see [comment](https://github.com/elastic/ingest-docs/pull/1090#discussion_r1626559373))
- Removes mention of the setting from the Fleet docs "[Enable agent monitoring](https://www.elastic.co/guide/en/fleet/master/agent-policy.html#change-policy-enable-agent-monitoring)" section, since I don't think the setting is available through the UI (Julia, please correct me if that's wrong).
> Fix liveness endpoint docs

- docs/en/ingest-management/troubleshooting/faq.asciidoc
A quick PR to add links to the top of the [FAQ page](https://www.elastic.co/guide/en/fleet/current/fleet-faq.html), for easier navigation.
Closes: #1118
> Add links at top of FAQ page

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.22 Fleet & Agent Release Notes:
- Fleet: no entries in [Kibana RN PR](https://github.com/elastic/kibana/pull/184470)
- Fleet Server: one entry in [Fleet Server BC1 changelog](https://github.com/elastic/fleet-server/tree/e6f9cb548146e2a3e946036a443078bcc943f7e9/changelog/fragments)
- Elastic Agent: no entries in [agent core BC1 changelog](https://github.com/elastic/elastic-agent/tree/b40ddd8a2769c6433dadb574f5c9e03788fb7a02/changelog/fragments)
---
> Add Fleet & Agent 7.17.22 Release Notes

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
- docs/en/ingest-management/tab-widgets/logging.asciidoc
This PR adds documentation for the feature introduced by https://github.com/elastic/elastic-agent/pull/4549
> Add Elastic-Agent event log documentation

- docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
This adds the 8.14.1 Fleet & Elastic Agent Release Notes:
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/186029)
* Fleet Server contents from [BC1 changelog](https://github.com/elastic/fleet-server/tree/06101c8732535c666358679ad12185d2bbb11392/changelog/fragments)
* Elastic Agent contents from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/53ce8888909e9abe2a00da45d7e275a10fabc8a6/changelog/fragments)
See [DOCS PREVIEW](https://ingest-docs_bk_1126.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.14.1.html)
Closes: #1125
> Add Fleet & Agent 8.14.1 Release Notes

- docs/en/ingest-management/security/certificates.asciidoc
This updates the [Configure SSL/TLS for self-managed Fleet Servers](https://www.elastic.co/guide/en/fleet/master/secure-connections.html) page to include the recently added [mTLS flags](https://github.com/elastic/elastic-agent/pull/4007). I also added the `--fleet-server-policy=fleet-server-policy` flag since it was missing, but I see it in the example from the mTLS flags PR.
Closes: https://github.com/elastic/ingest-docs/issues/1098
---
> Add mTLS flags to 'Configure SSL/TLS' docs

- docs/en/ingest-management/elastic-agent/configuration/examples/config-file-example-apache.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/examples/config-file-example-nginx.asciidoc
- docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
- docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-serverless.asciidoc
- docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
The "API key" link that appears on a few pages in the Fleet & Agent docs would be more helpful if it pointed to [these instructions](https://www.elastic.co/guide/en/fleet/current/grant-access-to-elasticsearch.html#create-api-key-standalone-agent) in the guide.
ADD: I noticed a couple of small things that need updating on the page about API keys, so they're fixed as well.
> Fix 'API key' link to point to Fleet & Agent instructions

- docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
> Fix Serverless variable in API key steps

- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Just fixing up the terminology a bit for  this section about [alerts](https://www.elastic.co/guide/en/fleet/master/monitor-elastic-agent.html#fleet-alerting). The term "enable" seems a bit inappropriate in the context of an alert, since it implies that the alert already exists.
> Change 'enable' to 'set up' for agent alerting

- docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
- docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-serverless.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Small change to remove a couple of notes saying that `sudo` is required for Elastic Agent commands.
Also, a small touch-up to a semi-related troubleshooting page.
Closes: #505
> Remove sudo restriction from standalone examples

- docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
This adds the 8.14.2 Fleet & Elastic Agent Release Notes:
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/186920)
* No new Fleet Server contents in [BC1 changelog](https://github.com/elastic/fleet-server/tree/849246d2433d3fa9ae980e1252f8b7e65d271292/changelog/fragments)
* Elastic Agent contents from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/fce8a9c6015e0021d235fbc6ce405e43707dfc7c/changelog/fragments)
See [DOCS PREVIEW](https://ingest-docs_bk_1141.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.14.2.html)
Closes: #1140
> Add Fleet & Agent 8.14.2 Release Notes

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/tab-widgets/download.asciidoc
Related to https://github.com/elastic/docs/pull/3029
Updates the links in files that are included in the Observability guide. The use of internal links are breaking the build in https://github.com/elastic/docs/pull/3029. 
cc @KOTungseth @lcawl
> Use external link in files used in multiple books

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
This updates the Fleet Server scalability page with a scaling tip running a large volume of agents.
Closes: #1156 
---
---
I also put a link at the top of the page to make sure people can find the scaling recommendations section.
> Add Fleet scaling recommendation: ES API key cache size

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- docs/en/ingest-management/elastic-agent/run-container-common/deploy-elastic-agent.asciidoc
This updates the [Running Elastic Agent in a container](https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html#_step_4_run_the_elastic_agent_image) instructions with the options required for running the container on a read-only file system.
Target: 8.15
Closes:: https://github.com/elastic/ingest-docs/issues/1152
I assumed that "STATE_PATH is a variable that should be replaced with the full path to the stateful directory to mount, but please correct me if that's wrong.
---
> Add read-only filesystem option for Elastic Agent on Docker

- docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
This adds the 8.14.3 Fleet & Elastic Agent Release Notes:
* No new Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/187928)
* No new Fleet Server contents in [BC1 changelog](https://github.com/elastic/fleet-server/tree/c80a3b16de03350fec26d0ae326bf8ca250dc2ba/changelog/fragments)
* Elastic Agent contents from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/2df2c10b10501e457b69ef94e0ada45304b2d1a9/changelog/fragments)
---
> Add Fleet & Agent 8.14.3 Release Notes

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/integrations/integrations-assets-best-practices.asciidoc
This adds a "Best practices for integrations assets" page as proposed in https://github.com/elastic/ingest-docs/issues/248
Please see [PREVIEW PAGE](https://ingest-docs_bk_1155.docs-preview.app.elstc.co/guide/en/fleet/master/integrations-assets-best-practices.html)
> Add best practices for using integration assets

- docs/en/ingest-management/data-streams.asciidoc
Starting from version 8.13, Elasticsearch [includes](https://github.com/elastic/kibana/pull/174855) the `ecs@mappings` component templates in all the index templates used in Elastic Agent integrations. 
As integrations adopt the `ecs@mappings` component template, index templates cloned following the "Tutorial: Customize data retention policies" may start having problems with mappings.
End users must update their cloned index templates by adding the `ecs@mappings` component template.
This PR added a note and instructions to the tutorial users about updating the cloned index template they created following this tutorial.
- relates: https://github.com/elastic/kibana/pull/174855
> Data Streams: Add ecs@mappings disclaimer for index templates cloned on ES < 8.13

- docs/en/ingest-management/fleet/fleet-deployment-models.asciidoc
This updates the [Deployment models](https://www.elastic.co/guide/en/fleet/current/fleet-deployment-models.html) page with a section for Fleet and Elastic Agent on ECK, linking to the ECK docs.
Rel: #1075
---
> Add ECK deployment type with link to docs

- docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
Feedback from real users.
Due to the limitation https://github.com/elastic/elastic-agent/issues/2784 (https://support.elastic.co/knowledge/f69b6e46), Fleet Server still keeps using the Elasticsearch host provided at enroll time instead of using the one in the policy.
Elastic agent & Fleet are working on overcoming the limitation via https://github.com/elastic/fleet-server/issues/3464 but we should add a big warning message about this.
This message should be backported to all versions, at least until we'll introduce the enhancements to take into account the ES hosts coming from the policy.
> [DOCS] Update Fleet Server guide - Fleet Server keeps using the ES host provided at install/enroll time.

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
This updates the Fleet & Agent docs with the `allow_older_version` setting that was added via https://github.com/elastic/beats/pull/36884
Closes: https://github.com/elastic/ingest-docs/issues/1135
Related Beats docs PR: https://github.com/elastic/beats/pull/40338
---
Fleet settings -> Elasticsearch output settings -> [Advanced YAML configuration](https://www.elastic.co/guide/en/fleet/current/es-output-settings.html#es-output-settings-yaml-config)
Configure standalone Elastic Agent -> Outputs -> [Elasticsearch](https://www.elastic.co/guide/en/fleet/current/elasticsearch-output.html)
> Add `allow_older_versions` setting

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.23 Fleet & Agent Release Notes:
- Fleet: No entries in [Kibana RN PR](https://github.com/elastic/kibana/pull/189448)
- Fleet Server: one entry in [Fleet Server BC1 changelog](https://github.com/elastic/fleet-server/tree/c8e0858bb3effb4bf78c29aba657cb98b0c2f3e3/changelog/fragments)
- Elastic Agent: no entries in [agent core BC1 changelog](https://github.com/elastic/elastic-agent/tree/bd0ffc1af3bb6c6b0b61e4324f8d9e905b60b45a/changelog/fragments) nor in [agent package BC1 changelog](https://github.com/elastic/elastic-agent/tree/132893e0e79f7378a0dd63a8266a3d01c82303f4/changelog/fragments)
This also fixes the variable used to link to Fleet Server issues and PRs.
---
> Add Fleet & Agent 7.17.23 Release Notes

- docs/en/ingest-management/fleet/air-gapped.asciidoc
As stated by @mrodm, we update the docker images every time a new version of a package gets published.
It's important to highlight this detail for users in air-gapped envs.
This should be backported to any version.
> [DOCS] Clarify cadence of updates to EPR image

- docs/en/ingest-management/fleet/air-gapped.asciidoc
This is a redo of https://github.com/elastic/ingest-docs/pull/1213 which is failing CI checks for reasons unrelated to the docs change.
> Update air-gapped install docs wrt ARM64

- docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
As suggested by Luca [here](https://github.com/elastic/ingest-docs/pull/1186#issuecomment-2265103140), since https://github.com/elastic/fleet-server/issues/3464 has merged, this removes the following warning from the [Fleet Server on-prem](https://www.elastic.co/guide/en/fleet/current/add-fleet-server-on-prem.html) install docs:
> Remove warning about Fleet Server using ES host at install/enroll time

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Please backport to all versions where the link is present.
> [DOCS] Update link

- docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
This adds a "technical preview" marker to the docs about [running Elastic Agent in unprivileged mode](http://localhost:8000/guide/elastic-agent-unprivileged.html).
> Add technical preview tag for agent unprivileged mode

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
From a discussion in Slack, some commands when run in unprivleged mode require a `sudo -u elastic-agent-user` prefix. 
See [Knowledge Base article](https://support.elastic.dev/knowledge/view/1d161cf8) for reference.
---
ADD: This also updates the command reference to mark the `elastic-agent privileged` and `elastic-agent unprivileged` as in technical preview mode, since I forgot to do that in https://github.com/elastic/ingest-docs/pull/1244
> Add note to 'unprivleged' agent docs about elastic-agent-user

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Following https://github.com/elastic/beats/pull/38767, let's warn of raw data being collected by the Elastic Agent diagnostic bundle.
> [DOCS] Warn about sensible information in Elastic Agent diagnostic

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This will backport the following commits from `8.15` to `main`:
- [[DOCS] Warn about sensible information in Elastic Agent diagnostic (#1255)](https://github.com/elastic/ingest-docs/pull/1255)
> [main] [DOCS] Warn about sensible information in Elastic Agent diagnostic (#1255)

- docs/en/ingest-management/integrations/upgrade-integration.asciidoc
This adds the list of integrations for which integration policies are updated automatically. It also makes clear for which of these you can opt-in to the auto-updates versus those for which the auto-updates can't be disabled.
Thanks @kpollich for the super clear description in the issue!
Closes: #1222
---
> Document list of auto-updated packages

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/otel-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
This is a redo of https://github.com/elastic/ingest-docs/pull/1095 reducing the docs that we include in the Fleet & Elastic Agent Guide. Full docs for running Elastic Agent as an OTel collector can be found in the [elastic/opentelemetry repo](https://github.com/elastic/opentelemetry/tree/main).
This updates the F&A Guide with:
- A brief intro: [Run Elastic Agent as an OTel Collector](https://ingest-docs_bk_1250.docs-preview.app.elstc.co/guide/en/fleet/master/otel-agent.html)
- The [`elastic-agent otel` command](https://ingest-docs_bk_1250.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-cmd-options.html#elastic-agent-otel-command)
FYI @ycombinator & @strawgate
> Add docs for agent 'otel' mode

- docs/en/ingest-management/agent-policies.asciidoc
This updates the [Elastic Agent policies page](http://localhost:8000/guide/agent-policy.html) with the new unenrollment timeout setting added via https://github.com/elastic/kibana/pull/189861
Target: 8.16
Closes: https://github.com/elastic/ingest-docs/issues/1225
Welcome back @criamico! Please let me know if I've missed anything.
Preview
---
> Add docs for agent unenrollment timeout setting

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
This updates the instructions for adding an integration to a policy. Those instructions appear in two places, in the "manage integrations" context and as part of the Fleet docs for managing Elastic Agent and agent policies. The content in both places is pretty much identical. I also did a little bit of reorganizing.
Target: 8.16
Closes: #1220 
---
> Update docs for reusable integrations policies

- docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
From a Slack thread with @jeanfabrice, this updates the default port settings on the three pages below to refer to "Kibana (Fleet)" rather than "Fleet":
- [Deploy on Elastic Cloud](https://www.elastic.co/guide/en/fleet/current/add-fleet-server-cloud.html)
- [Deploy on premises and self-managed](https://www.elastic.co/guide/en/fleet/current/add-fleet-server-on-prem.html)
- [Deploy Fleet Server on premises and Elasticsearch on Cloud](https://www.elastic.co/guide/en/fleet/current/add-fleet-server-mixed.html)
For example:
> Update port assignments from 'Fleet' to 'Kibana (Fleet)'

- docs/en/ingest-management/fleet/air-gapped.asciidoc
We should mention the supported TLS versions in the Fleet air-gapped docs, as Jaime suggests [here](https://github.com/elastic/ingest-docs/issues/1279#issuecomment-2326569596).
Closes: #1279 
---
> Add supported TLS version info to air-gapped docs

- docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
This adds the 8.15.1 Fleet & Elastic Agent Release Notes:
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/191871)
* Fleet Server: no new entries in [BC1 changelog](https://github.com/elastic/fleet-server/tree/d39870621bf812bfba536a9038958fca6ba7235e/changelog/fragments)
* Elastic Agent contents from [BC1 "core" changelog](https://github.com/elastic/elastic-agent/tree/edeb02e448d2f26070a023e63df429d30bbb91a6/changelog/fragments)
Closes: https://github.com/elastic/ingest-docs/issues/1277
---
> Add Fleet & Agent 8.15.1 Release Notes

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Apparently the setting `fleet-server-insecure-http` was removed by https://github.com/elastic/kibana/pull/129371
This updates the docs to remove mention of the removed setting.
Closes: https://github.com/elastic/ingest-docs/issues/1273
> Remove 'fleet-server-insecure-http' setting from docs

- docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
This change was originally not intended to be released in 8.15.1, but we are including it at the end.
https://github.com/elastic/kibana/pull/191730
> Add release notes for elastic/kibana#191730

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
This adds a known issue to the 8.12 Release Notes for the Remote ES / Elastic Defend bug.
Closes: https://github.com/elastic/ingest-docs/issues/1291
Thanks for providing the details @juliaElastic!
---
> Update 8.12 Release Notes for Remote ES / Elastic Defend bug

- docs/en/ingest-management/agent-policies-environment-variables.asciidoc
- docs/en/ingest-management/index.asciidoc
[Based on a Slack discussion] The Env Provider is available for use in Fleet-managed Elastic Agent (i.e., not only for standalone Elastic Agent), so this updates the Fleet-managed agent docs with a short section about that.
Closes: #1283
---
> Add section about Env Provider availability for Fleet-managed agent

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.24 Fleet & Agent Release Notes:
- Fleet: TBD [Kibana RN PR](TBD)
- Fleet Server: no new entries in [Fleet Server BC1 changelog](https://github.com/elastic/fleet-server/tree/7e17c51d72499b7eff1e1ab2e74d82ae5c04b1aa/changelog/fragments)
- Elastic Agent: no entries in [agent core BC1 changelog](https://github.com/elastic/elastic-agent/tree/bc2cbf4b71ba456adace751f9da04b065a4091a2/changelog/fragments)
---
> Add Fleet & Agent 7.17.24 Release Notes

- docs/en/ingest-management/security/enrollment-tokens.asciidoc
This adds some detail to clear up usage of Fleet enrollment tokens.
Thanks for the suggestions @jillguyonnet. Let me know if I've missed anything.
Closes: #1270 
---
> Why the token name must be unique.
I think it should be enough for users to know just that the names need to be unique. I added:
---
> Add an explanation around revoking tokens (marked as inactive, will be removed after expiration) with a link to the [retention period setting in Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#api-key-service-settings-delete-retention-period).
> A mention that inactive tokens are still returned by the GET API and visible in the UI until they are cleaned up.
---
> "enrollment tokens" in the docs vs. "enrollment API keys" in the OpenAPI …
> Fix up enrollment token docs

- docs/en/ingest-management/fleet/air-gapped.asciidoc
This updates section 1b) of [Host your own artifact registry for binary downloads](https://www.elastic.co/guide/en/fleet/current/air-gapped.html#host-artifact-registry) to expand on the package URL format. 
it's not perfect but I don't think we have a way of listing all possible package URLs, so at least providing the format and guiding people to refer to the Elastic Agent download page can help clear things up.
Closes: https://github.com/elastic/ingest-docs/issues/287
DOCS PREVIEW
---
> Document format for air-gapped downloadable packages

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Correct the wrong `connection_idle_timeout` with the correct `idle_connection_timeout` setting.
See https://github.com/search?q=repo%3Aelastic%2Fbeats%20idle_connection_timeout&type=code for reference
I think this is also wrong in the automated test: https://github.com/elastic/beats/blob/c75a7a4b3dab942e78fe4c8c48225811ad216b4b/x-pack/filebeat/input/netflow/integration_test.go#L102
> Correct incorrect connection_idle_timeout setting

- docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
This will backport the following commits from `8.15` to `main`:
- [Correct incorrect connection_idle_timeout setting (#1309)](https://github.com/elastic/ingest-docs/pull/1309)
> [main] Correct incorrect connection_idle_timeout setting (#1309)

- docs/en/ingest-management/elastic-agent/advanced-kubernetes-managed-by-fleet.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- docs/en/ingest-management/fleet/filter-agent-list-by-tags.asciidoc
- docs/en/ingest-management/fleet/fleet-server-secrets.asciidoc
- docs/en/ingest-management/tab-widgets/run-agent-image/content.asciidoc
Elastic Agent Docker images are currently available under both a `beats` and `elastic-agent` namespace. For 9.0 only the latter will be available, so in preparation for that this will update the current (8.15).
Closes: https://github.com/elastic/ingest-docs/issues/1314
> [Fleet & Agent docs] Change 'beats' namespace to 'elastic-agent'

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- docs/en/ingest-management/elastic-agent/run-container-common/download-elastic-agent.asciidoc
This fixes two links to use the newly created `elastic-agent` namespace rather than `beats`. 
Rel: https://github.com/elastic/ingest-docs/pull/1315#issuecomment-2349244946
> Change docker link from 'beats' to 'elastic-agent' namespace

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
This adds a few sentences to mention orphaned integrations, i.e., those that have been removed from and are no longer associated with any Elastic Agent policies.
@jen-huang Please let me know if I've missed anything.
Closes: #1261 
Rel: https://github.com/elastic/ingest-docs/issues/1220
This content appears in two spots:
- [Add an integration to an Elastic Agent policy](https://www.elastic.co/guide/en/fleet/master/add-integration-to-policy.html) (in the "Manage integrations" section of the docs)
- [Add an integration to a policy](https://www.elastic.co/guide/en/fleet/master/agent-policy.html#add-integration) (in the Agent Policies section of the docs)
---
> Add docs for orphaned integrations

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
This updates the docs with the extra steps required to install Elastic Agent as a Fleet Server in containerized environments.
**On Kubernetes**
- On the page "Run Elastic Agent on Kubernetes managed by Fleet" this updates "[Step 3: Enroll Elastic Agent to the policy](https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html#_step_3_enroll_elastic_agent_to_the_policy)" to add the following:
**In Docker**
- On the page "Run Elastic Agent in a container" this updates "[Step 4: Run the Elastic Agent image](https://www.elastic.co/guide/en/fleet/master/elastic-agent-container.html#_step_4_run_the_elastic_agent_image)"  to add the following:
---
Rel: https://github.com/elastic/ingest-docs/issues/1075
> Add Fleet Server install steps on K8s and Docker

- docs/en/ingest-management/fleet/fleet-deployment-models.asciidoc
This adds a "Docker and Kubernetes" section to the [Deployment models](https://www.elastic.co/guide/en/fleet/current/fleet-deployment-models.html) page, which provides links to the various ways of configuring Elastic Agents to work with Elasticsearch, via Fleet Server.
The links point to:
- [Run Elastic Agent in a container](https://www.elastic.co/guide/en/fleet/master/elastic-agent-container.html#_step_4_run_the_elastic_agent_image)
- [Run Elastic Agent on Kubernetes managed by Fleet](https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html#_step_3_enroll_elastic_agent_to_the_policy)
Both pages have been updated to include Fleet Server setup steps, via https://github.com/elastic/ingest-docs/pull/1184
---
**DOCS UPDATE**
> Add 'Docker and Kubernetes' to Deployment Models page

- docs/en/ingest-management/data-streams.asciidoc
Relates https://github.com/elastic/kibana/issues/190730
This PR update the [Fleet data stream docs](https://www.elastic.co/guide/en/fleet/current/data-streams.html) to document the new data stream type custom component template feature.
Before:
After:
> Add new data stream type custom component template to Fleet docs

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
This removes the Technical Preview admonitions from [Run Elastic Agent without administrative privileges](https://www.elastic.co/guide/en/fleet/current/elastic-agent-unprivileged.html) and from the associated commands on the Command Reference page.
> Remove technical preview markers for 'unprivileged' mode

- docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
This adds the 8.15.2 Fleet & Elastic Agent Release Notes:
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/193845)
* Fleet Server entry from [BC2 changelog](https://github.com/elastic/fleet-server/tree/68b764cdd2b55995f702bd0255ee4038e43e1df2/changelog/fragments)
* Elastic Agent contents from [BC2 changelog](https://github.com/elastic/elastic-agent/tree/621bbc685c2de8a2ad2c7c7f7cc1eb5fcf77d6d4/changelog/fragments)
Closes: https://github.com/elastic/ingest-docs/issues/1339
---
> Add Fleet & Agent 8.15.2 Release Notes

- docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
It was reported in Slack that on the [Kubernetes install instructions for standalone agent](_step_1_download_the_elastic_agent_manifest_3), customers are being directed to `8.15.2` manifest files before they're fully available.
Essentially this link:
`curl -L -O https://raw.githubusercontent.com/elastic/elastic-agent/8.15/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml`
Should be:
`curl -L -O https://raw.githubusercontent.com/elastic/elastic-agent/8.15.1deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml`
I've fixed this by changing the `{manifest}` variable to include `{bare-version}` (which is currently set to `8.15.1`) rather than `{branch}` (which is currently set to `8.15`).
The screen capture below shows the manifest link as `8.16.0` because this change is going …
> Fix standalone agent K8s manifest link to include patch level

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
A customer reported not being run Elastic Agent in Docker on Windows, which is not supported. This adds that restriction near the top of the [Run Elastic Agent in a container](https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html) page.
---
> Add restriction about containerized agent on Windows

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
- Update Logstash output (both Fleet managed EA & standalone EA)
- To share a more realistic configuration to the "reality" 
- Callout to the Fleet Output wizard in Fleet UI
- Update the Kafka output (both Fleet managed EA & standalone EA)
- To highlight we do not test this flow at the moment
- To suggest to disable `ecs_compatibility` both in input and codec when using the Kafka input in Logstash to dequeue items coming from EA and shipping them to Elasticsearch
Maintainers/reviewers:
- Improve wording (@davidkyle)
- Double check with PMs (@nimarezainia + @flexitrev) 
- FYI @jlind23 as discussed internally
> [Fleet/EA] Logstash & Kafka Outputs refresh

- docs/en/ingest-management/security/certificates.asciidoc
- docs/en/ingest-management/security/mutual-tls.asciidoc
This adds a note at the bottom of the Overview section on the [Elastic Agent deployment models with mutual TLS](https://www.elastic.co/guide/en/fleet/current/mutual-tls.html) page and the Prerequisites section of the [Configure SSL/TLS for self-managed Fleet Servers](https://www.elastic.co/guide/en/fleet/current/secure-connections.html#prereqs) page.
@AndersonQ, please fix this up however it should be worded because I have no idea what I'm talking about here. :-)
> Add note about elliptic-curve restriction

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
- docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
This will backport the following commits from `main` to `8.x`:
- [[Fleet/EA] Logstash & Kafka Outputs refresh (#1306)](https://github.com/elastic/ingest-docs/pull/1306)
> [8.x] [Fleet/EA] Logstash & Kafka Outputs refresh (#1306)

- docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Update the documentation to be in-line with https://github.com/elastic/elastic-agent/pull/5536. This is just for 9.0.
> Update env variables for ES authentication

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
This updates the [Enable agent monitoring](https://www.elastic.co/guide/en/fleet/current/agent-policy.html#change-policy-enable-agent-monitoring) section of the docs, renamed to "Configure agent monitoring", and adds the advanced monitoring options shown below.
This also removes the [Override the default monitoring port](https://www.elastic.co/guide/en/fleet/current/agent-policy.html#agent-policy-http-monitoring) section since that's replaced in the UI by the new monitoring options.
target: 8.16
closes: https://github.com/elastic/ingest-docs/issues/1333
I've also opened https://github.com/elastic/ingest-docs/issues/1362 as a separate issue to add a few missing options to the [Configure monitoring for standalone Elastic Agents](https://www.elastic.co/guide/en/fleet/current/elastic-agent-mon …
> Add docs for advanced monitoring options

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
This fixes the warning about running the `elastic-agent uninstall` to indicate that the command shouldn't be run from the directory where agent is installed. This appears in the [command reference](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-uninstall-command) and the [uninstall instructions page](https://www.elastic.co/guide/en/fleet/current/uninstall-elastic-agent.html#_uninstall_on_macos_linux_and_windows).
Closes: https://github.com/elastic/ingest-docs/issues/1364
Rel: https://github.com/elastic/sdh-beats/issues/5224#issuecomment-2391715465
---
> Fix uninstall warning about current directory

- docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
This updates the [Elastic Agent environment variables](https://www.elastic.co/guide/en/fleet/current/agent-environment-variables.html) page to add/remove variables as described [here](https://github.com/elastic/ingest-docs/issues/1075#issuecomment-2362112155).
For easier reviewing, I've copied the output into [this google doc](https://docs.google.com/document/d/10NH4LMPZksG2R7-sd3lKbxms_-PZzxpy05z4kfna7NE/edit).
Removed variables:
- `KIBANA_FLEET_SETUP ` has been removed for a while: https://github.com/elastic/elastic-agent/issues/2910
Added variables:
- `FLEET_FORCE` - same as the `--force flag`
- `ELASTIC_AGENT_CERT` & `ELASTIC_AGENT_CERT_KEY` - paths to mtls cert and key the agent will use to connect to fleet-server. (corresponding var for passphrase is missing)
- …
> Add missing environment variables for container setup

- docs/en/ingest-management/processors/processor-add_cloud_metadata.asciidoc
This PR adds documentation for the usage of `BEATS_ADD_CLOUD_METADATA_PROVIDERS` environment variable.
This variable is alternative way of configuring the list of cloud providers that the processor needs to detect.
It helps in cases where the processor fails to correctly detect the cloud provider.
> Add documentation in add_cloud_metadata processor about the usage of BEATS_ADD_CLOUD_METADATA_PROVIDERS env var

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
This adds a section to the [Fleet settings](https://www.elastic.co/guide/en/fleet/master/fleet-settings.html) page for the new 'Delete unenrolled agents' option.
Targets 8.16
Closes: #1376
---
> Add docs for 'delete unenrolled agents'

- docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
This adds the 8.15.3 Fleet & Elastic Agent Release Notes:
* No Fleet contents in [Kibana Release Notes PR]()
* No Fleet Server entries in [BC1 changelog](https://github.com/elastic/fleet-server/tree/68b764cdd2b55995f702bd0255ee4038e43e1df2/changelog/fragments)
* Elastic Agent contents from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/621bbc685c2de8a2ad2c7c7f7cc1eb5fcf77d6d4/changelog/fragments)
---
> Add Fleet & Agent 8.15.3 Release Notes

- docs/en/ingest-management/integrations/integration-level-outputs.asciidoc
This adds a restriction to the [integration-level outputs](https://www.elastic.co/guide/en/fleet/master/integration-level-outputs.html) page.
> Add note: integration-level outputs must be at same sub level

- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/elastic-agent-kubernetes-autodiscovery.asciidoc
This will backport the following commits from `8.15` to `main`:
- [Update elastic-agent-kubernetes-autodiscovery.asciidoc (#1391)](https://github.com/elastic/ingest-docs/pull/1391)
> [main] Update elastic-agent-kubernetes-autodiscovery.asciidoc (#1391)

- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/elastic-agent-kubernetes-autodiscovery.asciidoc
This will backport the following commits from `8.15` to `8.x`:
- [Update elastic-agent-kubernetes-autodiscovery.asciidoc (#1391)](https://github.com/elastic/ingest-docs/pull/1391)
> [8.x] Update elastic-agent-kubernetes-autodiscovery.asciidoc (#1391)

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.24 Fleet & Agent Release Notes:
- Fleet: No entries in [Kibana RN PR](https://github.com/elastic/kibana/pull/196498)
- Fleet Server: no new entries in [Fleet Server BC1 changelog](https://github.com/elastic/fleet-server/tree/7e17c51d72499b7eff1e1ab2e74d82ae5c04b1aa/changelog/fragments)
- Elastic Agent: no entries in [agent core BC1 changelog](https://github.com/elastic/elastic-agent/tree/bc2cbf4b71ba456adace751f9da04b065a4091a2/changelog/fragments)
---
> Add Fleet & Agent 7.17.25 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
- Relates https://github.com/elastic/beats/issues/41355
The same as https://github.com/elastic/beats/pull/41379 but for agent instead.
> Add known issue for 8.15.x memory increase.

- .mergify.yml
Adds the ability to use `backport-main` to backport to `main`.
Useful when contributors use `edit` links in the public documentation.
> Add the ability to backport to `main`

- docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.yml
We had feedback on the [Reference YAML](https://www.elastic.co/guide/en/fleet/current/elastic-agent-reference-yaml.html) docs page asking where to find a description of each field.
This PR:
- Refreshes the embedded `elastic-agent.reference.yml` file with the version from `8.16`.
- Updates the paragraph at the top with links to the original version of the file in the elastic-agent repo, and to the docs section where the setting descriptions live.
Closes: https://github.com/elastic/docs-feedback/issues/47
---
> Update docs version of reference.yml and improve header section

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
- docs/en/ingest-management/security/certificates.asciidoc
- docs/en/ingest-management/security/mutual-tls.asciidoc
- docs/en/ingest-management/security/tls-overview.asciidoc
elastic/elastic-agent#5494 added support for the `--elastic-agent-cert-key-passphrase` option.  This PR adds the missing user facing documentation.
This option is only used if the `--elastic-agent-cert-key` is encrypted and requires a passphrase to use.
> Add documentation for elastic-agent-cert-key-passphrase option

- docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
The updates [View agent status overview](https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html#view-agent-status) to note that the table is limited to 10k records.
Closes: #296
---
---
This also adds a note about the table sorting:
---
> Add a note about the agent status table limit of 10k records

- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
At the top of the [Kafka output settings](https://www.elastic.co/guide/en/fleet/current/kafka-output-settings.html#_kafka_output_and_using_logstash_to_index_data_to_elasticsearch) page is a section warning users about potential problems when they use use Logstash to modify the Kafka output on its way to Elasticsearch. It's not ideal for all users to start their Kafka output journey with that section.
I think it'd be better to have that section at the bottom of the Kafka output settings page, and to make sure people find the section we can add a warning at the top of the page, like this:
---
The guidance for Logstash appears just as before, but at the bottom of the page:
---
---
@lucabelluccini, @nimarezainia  Any thoughts or concerns?
> Move section about Logstash to bottom of Kafka output page

- docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
Update the 8.13 release notes to add a known issue.
Due to changes introduced to support the ecs@mappings component template (see https://github.com/elastic/kibana/pull/174855[elastic/kibana/pull/174855), Fleet no longer includes ECS fields to the integrations' `index.query.default_field`. 
This may affect integrations that rely on fieldless queries (when no field is specified for a query).
This PR updates the 8.13 release notes to 
- acknowledge the problem
- inform users that 8.14 is not affected
- suggest a workaround to 8.13 users
Relates https://github.com/elastic/integrations/issues/10848
> Add ECS known issue for ecs@mappings and fieldless searches

- docs/en/ingest-management/elastic-agent/install-agent-msi.asciidoc
Rephrased to clarify that upgrades via fleet are supported, but the impact is that the MSI version remains registered at the initially installed package version. Added suggestion for MSI installs (package management) that in order to upgrade an uninstall/reinstall is required.
> Clarification of MSI Upgrading Behavior

- docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Update Elastic Agent documents to indicate that the protocol version should be set to at least `2.1.0` when using Kafka 4.0
Related:
https://github.com/elastic/integrations/pull/11655
https://github.com/elastic/beats/pull/41540
> Update Kafka Output settings documentation to indicate minimum version value for Kafka 4.0

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Closes: https://github.com/elastic/ingest-dev/issues/4366
> Update the elastic-agent resource consumption docs

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Removing the word "total" from the agent resource requirements table to make the columns consistent on CPU metrics.
> Wording tweak to agent resource requirements table

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This adds the 8.16.0 Fleet & Elastic Agent Release Notes:
* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/198166)
* Fleet Server contents from [BC3 changelog](https://github.com/elastic/fleet-server/tree/7f12dbd1abf6ceed06fbe4eb96fe1cc3e1b20219/changelog/fragments)
* Elastic Agent contents from [BC3 changelog](https://github.com/elastic/elastic-agent/tree/6c0d2398399dfbf6a4f5d95e3e55a138fee9a737/changelog/fragments)
See [DOCS PREVIEW](https://ingest-docs_bk_1412.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.16.0.html)
Closes: https://github.com/elastic/ingest-docs/issues/1411
> Add Fleet & Agent 8.16.0 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
This adds the 8.15.4 Fleet & Elastic Agent Release Notes:
* No Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/198565)
* No Fleet Server contents in [BC1 changelog](https://github.com/elastic/fleet-server/tree/940c4d76aa0a8d48b508c51615a0def586974494/changelog/fragments)
* No Elastic Agent contents in [BC1 changelog](https://github.com/elastic/elastic-agent/tree/099e5882ccda4cbc344ab8cc8f18e631325fa439/changelog/fragments)
---
> Add Fleet & Agent 8.15.4 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
There was a copy/paste error linking to the network connection issue in the wrong place.
> Fix link to 8.15.x memory queue issue in Beats.

- docs/en/ingest-management/fleet/api-generated/rules/fleet-apis-passthru.asciidoc
This change documents the ability to leverage a `batchSize` body parameter for the `bulk_reassign_agents_request` which was introduced in the following PR: https://github.com/elastic/kibana/pull/134565
This will also help align the documentation with the following Kibana API docs: https://www.elastic.co/docs/api/doc/kibana/operation/operation-post-fleet-agents-bulk-reassign
> Update bulk_reassign_agents_request to include batchSize body parameter

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This adds the 8.16.1 Fleet & Elastic Agent Release Notes:
* No Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/200693)
* No Fleet Server contents in [BC1 changelog](https://github.com/elastic/fleet-server/tree/98286a5d8869e04e3ff8920b915e86770d89f458/changelog/fragments)
* Elastic Agent contents from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/b6da7f8ebb1d0d06c1f1929dfed8458708a5bedf/changelog/fragments)
Closes: https://github.com/elastic/ingest-docs/issues/1485
---
> Add Fleet & Agent 8.16.1 Release Notes

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Requested by NIma, this adds a note to emphasize the new reusuable integration policies feature.
> Add mention of reusable integration policies

- docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
This adds the 8.15.5 Fleet & Elastic Agent Release Notes:
* No Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/201050)
* No Fleet Server contents in [BC2 changelog](https://github.com/elastic/fleet-server/tree/2782f7f6466ede97855ed14b014161d059820d0c/changelog/fragments)
* Elastic Agent contents in [BC2 changelog](https://github.com/elastic/elastic-agent/tree/1672605efebb153e23fb89aabe160b2bf0403d93/changelog/fragments)
Closes: https://github.com/elastic/ingest-docs/issues/1497
---
> Add Fleet & Agent 8.15.5 Release Notes

- docs/en/ingest-management/fleet/air-gapped.asciidoc
Typo fix: "om" replaced with "in"
> Fixed very small typo in air-gapped.asciidoc

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.26 Fleet & Agent Release Notes:
- Fleet: No entries in [Kibana RN PR](https://github.com/elastic/kibana/pull/202122)
- Fleet Server: no new entries in [Fleet Server BC1 changelog](https://github.com/elastic/fleet-server/tree/8990f4d35031af38de09b9a460b850823fec6664/changelog/fragments)
- Elastic Agent: no entries in [agent core BC1 changelog](https://github.com/elastic/elastic-agent/tree/5b41c60f8a028d1a883be72fb157a1c4ea8aa911/changelog/fragments)
---
> Add Fleet & Agent 7.17.26 Release Notes

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
This adds docs for running Elastic Agent unprivileged mode, as a specific user or group (e.g. under an Active Directory account).
Targets: 8.x
Closes: #1503
---
**Update to [Run Elastic Agent without administrative privileges](https://www.elastic.co/guide/en/fleet/master/elastic-agent-unprivileged.html) page:**
---
**Update to Command Reference [`elastic-agent install` command](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-install-command) `--unprivileged` option:**
---
**Update to Command Reference [`elastic-agent unprivileged` command](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-unprivileged-command):**
> Add docs for running unprivileged agent as existing user/group

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This adds docs for the known issues:
- "no agent found", described in Knowledge Center [here](https://support.elastic.dev/knowledge/view/6d9d7467).
- Fleet-managed agent throws an exception on uninstall in Windows, described in Knowledge Center [here](https://support.elastic.dev/knowledge/view/56de5be4).
Closes:  #1481
Closes: #1482
I'll update the "Impact" section of the second issue as soon as we have a suggested workaround (Blake or Craig, if you can please let me know once we have that).
---
> Add known issues for 'no agent found', Agent uninstall exception

- docs/en/ingest-management/commands.asciidoc
This updates a few spots in the command reference to use the super handy, inline "technical preview" tag which I didn't know we had.
---
> Use correct technical preview tags

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
This adds the 8.17.0 Fleet & Elastic Agent Release Notes:
* Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/202021)
* Fleet Server contents in [BC6 changelog](https://github.com/elastic/fleet-server/tree/d6f955edbebfd348e37504f8bbcb0848746e4c35/changelog/fragments)
* Elastic Agent contents from [BC6 changelog](https://github.com/elastic/elastic-agent/tree/96f2b9fc0dbddfcaac1c55e0e0bc9aed3bf6badb/changelog/fragments)
See [preview page](https://ingest-docs_bk_1498.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.17.0.html)
Closes: https://github.com/elastic/ingest-docs/issues/1487
> Add Fleet & Agent 8.17.0 Release Notes

- docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
This adds steps in the [Upgrade Fleet-managed Elastic Agents](https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html) page for upgrading DEB and RPM-based agent installs manually, since these upgrades are supported in Fleet.
Rel: https://github.com/elastic/ingest-docs/issues/133
---
> Add agent upgrade steps for DEB & RPM

- docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
This rephrases the version compatibility statement in the Fleet Server install docs to be a little bit more clear.
> Fix version compatibility statement

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
This adds the download instructions for the new Wolfi container install images for Elastic Agent.
@leemthompo Thanks for finding out about the wording we should use!
> Add download steps for Wolfi container images

- docs/en/ingest-management/elastic-agent/otel-agent-transform.asciidoc
- docs/en/ingest-management/elastic-agent/otel-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
This adds a placeholder where the "how to transform an agent to run as an OTel collector" will eventually land.
The `include` statement is commented out so this PR has no visible effect in the current docs.
Closes: #1549
---
> Add placeholder for 'transform to OTel Collector' docs

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This adds the 8.16.2 Fleet & Elastic Agent Release Notes:
* No new Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/204126)
* No new Fleet Server contents in [BC1 changelog](https://github.com/elastic/fleet-server/tree/2d32c2841a221d2a24694aca77bf97443cb90549/changelog/fragments)
* Elastic Agent contents from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/05896198ad3cbb41c61d403c9c33b11f8bebd39a/changelog/fragments)
* The note about Wolfi images is requested in https://github.com/elastic/dev/issues/2926
Closes: https://github.com/elastic/ingest-docs/issues/1528
---
> Add Fleet & Agent 8.16.2 Release Notes

- docs/en/ingest-management/agent-policies.asciidoc
- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
This updates the policy scaling recommendation that appears [here](https://www.elastic.co/guide/en/fleet/current/fleet-server-scalability.html#agent-policy-scaling-recommendations) and [here](https://www.elastic.co/guide/en/fleet/current/agent-policy.html#agent-policy-scale). The recommendation is updated for stateful and added in for Serverless, which we previously didn't mention.
@kpollich  Should this target just 8.x, or is 8.17 also updated?
Closes: https://github.com/elastic/ingest-docs/issues/1551
---
> Update policy scaling recommendation

- docs/en/ingest-management/elastic-agent/otel-agent-transform.asciidoc
Quick documentation about configuring an installed, standalone Elastic Agent to run as OTel Collector (possible thanks to https://github.com/elastic/elastic-agent/pull/5767).
Closes https://github.com/elastic/elastic-agent/issues/4933
> Add small doc about running a standalone agent in otel mode

- docs/en/ingest-management/elastic-agent/otel-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
This enables the new "Transform an installed Elastic Agent to run as an OTel Collector" docs. The page had been created but commented out.
No need to backport. In 8.x these are enabled via https://github.com/elastic/ingest-docs/pull/1559
> Enable new agent -> OTel-agent transform docs

- docs/en/ingest-management/elastic-agent/configuration/authentication/ssl-settings.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.yml
Remove TLSv1.0 from supported_protocols list and set defaults to TLSv1.2, TLSv1.3 for the 9.x release
- Relates https://github.com/elastic/elastic-agent/issues/5996
- Relates https://github.com/elastic/fleet-server/issues/4107
> Remove TLSv1.0 from supported protocols

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
This updates the [Run Elastic Agent in a container](https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html) page with a link to the blog article about why the Wolfi images were introduced.
Rel: #1608 
Associated Beats PR: https://github.com/elastic/beats/pull/42268
---
> Add details for Wolfi install image

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This updates the 8.16.0 release notes as shown:
---
Closes: https://github.com/elastic/ingest-docs/issues/1613
> known issue for when an integration level output is set to default

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.27 Fleet & Agent Release Notes:
- Fleet: No changes in [Kibana RN PR](https://github.com/elastic/kibana/pull/206347)
- Fleet Server: no new entries in [Fleet Server BC1 changelog](https://github.com/elastic/fleet-server/tree/d697a1da15f6f574171f9c99cfedcdb36f1b895a/changelog/fragments)
- Elastic Agent: no entries in [agent core BC1 changelog](https://github.com/elastic/elastic-agent/tree/0581ff6591512ea0a39137fa09fe4094db758f61/changelog/fragments)
---
> Add Fleet & Agent 7.17.27 Release Notes

- docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc
This updates the Provider docs to indicate that providers are no longer enabled by default, as a result of https://github.com/elastic/elastic-agent/pull/6169
- The main change is to [Configure providers for standalone Elastic Agent](https://www.elastic.co/guide/en/fleet/current/providers.html): 
- I've also updated the [Kubernetes LeaderElection Provider](https://www.elastic.co/guide/en/fleet/current/kubernetes_leaderelection-provider.html)
- I don't think any other providers pages need updating. The [Kubernetes provider](https://www.elastic.co/guide/en/fleet/current/kubernetes-provider.html) supports enabling individual resources (pods, nodes, or services), but I assume the defaults for that remain as is.
---
Closes: https://github.com/elastic/ingest-docs/issues/1529
Target: 8.18
> Update docs to indicate that providers are no longer enabled by default

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This adds the 8.16.3 Fleet & Elastic Agent Release Notes:
* Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/206156)
* No new Fleet Server contents in [BC1 changelog](https://github.com/elastic/fleet-server/tree/915f0aeb9aa1e9c293224f4af66e86d09560f648/changelog/fragments)
* No new Elastic Agent contents in [BC1 changelog](https://github.com/elastic/elastic-agent/tree/5f3c247f70bffffe9764eb8592c2a067e5f57e5b/changelog/fragments)
Rel: https://github.com/elastic/ingest-docs/issues/1611
---
> Add Fleet & Agent 8.16.3 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
This adds the 8.17.1 Fleet & Elastic Agent Release Notes:
* Fleet, no content in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/206157)
* Fleet Server contents from [BC2 changelog](https://github.com/elastic/fleet-server/tree/4caf6ac0d6d60c79bb47c9a02b8c5754c43ca566/changelog/fragments)
* Elastic Agent contents from [BC2 changelog](https://github.com/elastic/elastic-agent/tree/b8183acb1e8387b56ea46117e7f51e5300cfa5c0/changelog/fragments)
See [preview page](https://ingest-docs_bk_1612.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.17.1.html)
Closes: https://github.com/elastic/ingest-docs/issues/1611
> Add Fleet & Agent 8.17.1 Release Notes

- docs/en/ingest-management/data-streams.asciidoc
This adds the restrictions described in https://github.com/elastic/ingest-docs/issues/1618 to the [Enabling and disabling advanced indexing features for Fleet-managed data streams](https://www.elastic.co/guide/en/fleet/current/data-streams-advanced-features.html) page.
I also removed some extra spacing which I must have added earlier by accident.
@lucabelluccini and @martijnvg, please check that I have the `enable` and `disable` code examples right, since I'm kind of guessing. 
Closes: https://github.com/elastic/ingest-docs/issues/1618
**Previews:**
--- 
---
> Add restrictions for synthetic `_source`

- docs/en/ingest-management/fleet/fleet-settings-remote-elasticsearch.asciidoc
This updates the [Remote Elasticsearch output](https://www.elastic.co/guide/en/fleet/current/remote-elasticsearch-output.html) page with the following warning:
---
Closes: https://github.com/elastic/ingest-docs/issues/1638
> Add warning about Elastic Defend with remote ES output

- docs/en/ingest-management/agent-policies.asciidoc
Reusable integration feature requires enterprise license.
https://github.com/elastic/kibana/issues/188707
> [Reusable integration] GA on 8.16 requires Enterprise License

- docs/en/ingest-management/fleet/add-fleet-server-kubernetes-content.asciidoc
- docs/en/ingest-management/fleet/add-fleet-server-kubernetes.asciidoc
- docs/en/ingest-management/fleet/air-gapped.asciidoc
- docs/en/ingest-management/index.asciidoc
Adding a `Deploy Fleet Server on Kubernetes` document, under `Deployment models` section.
Preview: https://ingest-docs_bk_1518.docs-preview.app.elstc.co/guide/en/fleet/master/add-fleet-server-kubernetes.html
> Fleet Server on kubernetes document proposal

- docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/fleet/air-gapped.asciidoc
This adds instructions for air-gapped environments on how to set `server.pgp.upstream_url` so that Elastic Agents can access the PGP/GPG key required for upgrade.
See [docs preview page](https://ingest-docs_bk_984.docs-preview.app.elstc.co/guide/en/fleet/master/air-gapped.html#air-gapped-pgp-fleet).
Please let me know if I've missed anything, especially in the "Note that" section under the steps.
Closes: #980 
Rel: https://github.com/elastic/sdh-beats/issues/4496
> Add steps to configure a PGP key for agent upgrade

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This adds the 8.16.4 Fleet & Elastic Agent Release Notes:
* No Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/210108)
* Fleet Server [BC3 changelog](https://github.com/elastic/fleet-server/tree/7b13998120181a28537f6192fbe69a9e45a148d7/changelog/fragments)
* Elastic Agent [BC3 changelog](https://github.com/elastic/elastic-agent/tree/7be8f159c3b1eea7d7ac572e4f1dbda75f10aaa4/changelog/fragments)
Rel: https://github.com/elastic/ingest-docs/issues/1666
---
> Add Fleet & Agent 8.16.4 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
This adds the 8.17.2 Fleet & Elastic Agent Release Notes:
* No Fleet content in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/210109)
* Fleet Server contents from [BC1 changelog](https://github.com/elastic/fleet-server/tree/65cfce520ccb7d8884b8c31df883dab1b6ae0e79/changelog/fragments)
* Elastic Agent contents from [BC2 changelog](https://github.com/elastic/elastic-agent/tree/29bc86217c8134c715661f89afb601f0093fc845/changelog/fragments)
---
> Add Fleet & Agent 8.17.2 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Adds a known issue to the 8.17.1 release notes.
@kpollich Thanks for the super clear issue! I'll merge this on Tuesday when the 8.17.2 release is live, so that the option to upgrade is available.
Closes: https://github.com/elastic/ingest-docs/issues/1671
---
> Add known issue for Kibana OOM crashes

- docs/en/ingest-management/fleet/air-gapped.asciidoc
Small PR to replace `windows_x86_64` with `windows-x86_64`
```diff
$ curl -I https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.12.1-windows_x86_64.zip          
-HTTP/2 404 
date: Tue, 11 Feb 2025 21:29:27 GMT
strict-transport-security: max-age=31536000; includeSubDomains
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```
```diff
$ curl -I https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.12.1-windows-x86_64.zip
+HTTP/2 200 
date: Tue, 11 Feb 2025 21:30:57 GMT
content-type: application/zip
content-length: 294014409
accept-ranges: bytes
last-modified: Tue, 06 Feb 2024 09:25:28 GMT
etag: "078e7b61ea7aecc867bd8ceb81a986e2"
cache-control: public, max-age=600
strict-transport-security: max-age=31536000; …
```
> Typo fix in air-gapped.asciidoc

- docs/en/ingest-management/commands.asciidoc
The documentation page https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html erroneously reports that the flag `--non-interactive` can be used with the the `elastic-agent enroll` command.
This is not the case. If we execute enroll with this flag, we receive the following error:
> unknown flag: --non-interactive
This is also confirmed by the execution of `elastic-agent enroll --help`:
<details>
<summary>COMMAND OUTPUT</summary>
```
MYSHELL$ ./elastic-agent enroll --help
This command will enroll the Elastic Agent into Fleet.
Usage:
elastic-agent enroll [flags]
Flags:
-p, --ca-sha256 string                                Comma-separated list of certificate authority hash pins for server verification used by Elastic Agent and Fleet Server
-a, --certificate-authorities …
```
> [Elastic-Agent] Remove flag --non-interactive from the enroll documentation

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
Warn LS pipeline should not modify fields coming from EA
Modifying data coming from EA can prevent the ingest pipelines on Elasticsearch side associated to the integrations in use in EA to work correctly.
> [DOCS] Warn LS pipeline should not modify fields coming from EA

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
This adds the 7.17.27 Fleet & Agent Release Notes:
- Fleet: (probably) No changes in [Kibana RN PR - TBD]()
- Fleet Server: Entries from [Fleet Server BC1 changelog](https://github.com/elastic/fleet-server/tree/a780f745ac01af74a5b42e560946f031a9eafb74/changelog/fragments)
- Elastic Agent: No entries in [agent core BC1 changelog](https://github.com/elastic/elastic-agent/tree/1348b9ca7bff4d9bb7b0507e2524fbdaa8a85358/changelog/fragments)
Closes: https://github.com/elastic/ingest-docs/issues/1686
---
> Add Fleet & Agent 7.17.28 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Fixes a broken link, and also allows me to search for the PR when building RNs manually.
> Fix link in 8.17.2 release notes

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This adds the 8.16.5 Fleet & Elastic Agent Release Notes:
* No Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/212688)
* No new contents in Fleet Server [BC1 changelog](https://github.com/elastic/fleet-server/tree/922b5fb21812dd3bc368802131c55afb4da87741/changelog/fragments)
* No new contents in Elastic Agent [BC1 changelog](https://github.com/elastic/elastic-agent/tree/9608fdf8972c5e43b7007105a030107b15ceb936/changelog/fragments)
Rel: https://github.com/elastic/ingest-docs/issues/1699
---
> Add Fleet & Agent 8.16.5 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
This adds the 8.17.3 Fleet & Elastic Agent Release Notes:
* No Fleet content in [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/212693)
* No new Fleet Server contents  [BC1 changelog](https://github.com/elastic/fleet-server/tree/65cfce520ccb7d8884b8c31df883dab1b6ae0e79/changelog/fragments)
* Elastic Agent contents from [BC1 changelog](https://github.com/elastic/elastic-agent/tree/29bc86217c8134c715661f89afb601f0093fc845/changelog/fragments)
Closes: https://github.com/elastic/ingest-docs/issues/1699
---
> Add Fleet & Agent 8.17.3 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
This will backport the following commits from `8.x` to `8.16`:
- [Add Fleet & Agent 8.16.5 Release Notes (#1711)](https://github.com/elastic/ingest-docs/pull/1711)
> [8.16] Add Fleet & Agent 8.16.5 Release Notes (#1711)

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
- [Add Fleet & Agent 8.16.5 Release Notes (#1711)](https://github.com/elastic/ingest-docs/pull/1711)
> [8.18] Add Fleet & Agent 8.16.5 Release Notes (#1711)

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
- [Add Fleet & Agent 8.17.3 Release Notes (#1709)](https://github.com/elastic/ingest-docs/pull/1709)
> [8.18] Add Fleet & Agent 8.17.3 Release Notes (#1709)

- .backportrc.json
Since we're now merging docs changes into the `8.x` branch rather than `main`, we'll need to update the `8.x` version of `.backportrc.json` with the latest branches to backport to.
> Update .backportrc.json to include latest releases

- docs/en/ingest-management/elastic-agent/install-elastic-agent-in-container.asciidoc
- docs/en/ingest-management/fleet/enrollment-handling-containerized-agent.asciidoc
- docs/en/ingest-management/fleet/unenroll-elastic-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
- [Add page for enrollment handling in containerized environments (#1728)](https://github.com/elastic/ingest-docs/pull/1728)
> [8.18] Add page for enrollment handling in containerized environments (#1728)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
The [Variables and conditions in input configurations](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) is important for users and not easy to find. I think the location makes sense, but for better discoverability perhaps adding a prominent note to the [Install Elastic Agents](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html) main page can help:
We can add this note elsewhere as well, if that makes sense.
Rel: https://github.com/elastic/elastic-agent/issues/7284#issuecomment-2716079450
> Add tip about dynamic inputs to install page

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- [Add tip about dynamic inputs to install page (#1731)](https://github.com/elastic/ingest-docs/pull/1731)
> [8.18] Add tip about dynamic inputs to install page (#1731)

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Adds the 8.16.6 Release Notes.
Fleet contents from: https://github.com/elastic/kibana/pull/215252
Agent contents from: https://github.com/elastic/elastic-agent/pull/7523
---
> Add Fleet & Agent 8.16.6 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
This will backport the following commits from `8.x` to `8.17`:
- [Add Fleet & Agent 8.17.4 Release Notes (#1740)](https://github.com/elastic/ingest-docs/pull/1740)
> [8.17] Add Fleet & Agent 8.17.4 Release Notes (#1740)

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
- [Add Fleet & Agent 8.17.4 Release Notes (#1740)](https://github.com/elastic/ingest-docs/pull/1740)
> [8.18] Add Fleet & Agent 8.17.4 Release Notes (#1740)

- docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
- [Add Fleet & Agent 8.16.6 Release Notes (#1739)](https://github.com/elastic/ingest-docs/pull/1739)
> [8.18] Add Fleet & Agent 8.16.6 Release Notes (#1739)

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Adds the 8.17.5 Release Notes:
Fleet contents from: https://github.com/elastic/kibana/pull/217919
Fleet Server contents from: [Changelog file](https://github.com/elastic/fleet-server/tree/20f1ee7c3a65fdf500a044112913cea21faa86f6/changelog/fragments)
Elastic Agent contents from: https://github.com/elastic/elastic-agent/pull/7830
Closes: https://github.com/elastic/ingest-docs/issues/1760
---
> Add Fleet & Agent 8.17.5 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
- [Add Fleet & Agent 8.17.5 Release Notes (#1761)](https://github.com/elastic/ingest-docs/pull/1761)
> [8.18] Add Fleet & Agent 8.17.5 Release Notes (#1761)

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
This will backport the following commits from `8.x` to `8.17`:
- [Add Fleet & Agent 8.17.5 Release Notes (#1761)](https://github.com/elastic/ingest-docs/pull/1761)
> [8.17] Add Fleet & Agent 8.17.5 Release Notes (#1761)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This updates the install sizings for Elastic Agent. The change has been reviewed by Nima. We're intentionally including 9.0 in the table.
---
> Update Elastic Agent binary sizes

- docs/en/ingest-management/fleet/fleet-settings-remote-elasticsearch.asciidoc
A straightforward backport of https://github.com/elastic/docs-content/pull/1307 into the 8.18+ docs.
Rel: https://github.com/elastic/docs-content/issues/1201
> [Backport] Add note about remote ES error with Fleet Server

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Adds the 8.17.6 Release Notes:
Fleet contents TBD: (I'll add this when the Kibana release notes PR is ready, if there is anything)
No new Fleet Server contents in: [Changelog file](https://github.com/elastic/fleet-server/tree/09a9a5d893f58b0d1f54d5cbb36bee9fe319fb15/changelog/fragments)
Elastic Agent contents from: https://github.com/elastic/elastic-agent/pull/8062
---
> Add Fleet & Agent 8.17.6 Release Notes

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
- [Add Fleet & Agent 8.17.6 Release Notes (#1789)](https://github.com/elastic/ingest-docs/pull/1789)
> [8.18] Add Fleet & Agent 8.17.6 Release Notes (#1789)

- docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
This will backport the following commits from `8.x` to `8.17`:
- [Add Fleet & Agent 8.17.6 Release Notes (#1789)](https://github.com/elastic/ingest-docs/pull/1789)
> [8.17] Add Fleet & Agent 8.17.6 Release Notes (#1789)

- docs/en/ingest-management/release-notes/release-notes-8.18.asciidoc
- [Add Fleet & Agent 8.18.1 Release Notes (#1791)](https://github.com/elastic/ingest-docs/pull/1791)
> [8.18] Add Fleet & Agent 8.18.1 Release Notes (#1791)
